smallstep/certificates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE
Add templates for pull requests and bug reports
> Add templates for PR and bug reports.

- README.md
- docs/common-questions.md
- docs/recommendations.md
- server/server.go
Fix a couple typos and a markdown formatting issue.
> Fix a couple typos in documentation and a formatting issue

- authority/config.go
- authority/provisioner.go
- authority/types.go
- authority/types_test.go
> make Duration wrapper publicly accessible

- autocert/examples/hello-mtls/README.md
- autocert/examples/hello-mtls/py-gunicorn/Dockerfile.client
- autocert/examples/hello-mtls/py-gunicorn/Dockerfile.server
- autocert/examples/hello-mtls/py-gunicorn/client.py
- autocert/examples/hello-mtls/py-gunicorn/client.requirements.txt
- autocert/examples/hello-mtls/py-gunicorn/gunicorn.conf
- autocert/examples/hello-mtls/py-gunicorn/hello-mtls.client.yaml
- autocert/examples/hello-mtls/py-gunicorn/hello-mtls.server.yaml
- autocert/examples/hello-mtls/py-gunicorn/requirements.txt
- autocert/examples/hello-mtls/py-gunicorn/server.py
This PR adds a new example running gunicorn + Flask application and a python client.
> Hello mtls python client + gunicorn server

- docs/GETTING_STARTED.md
- examples/README.md
- examples/pki/config/ca.json
Since we've received questions about how to customize validity for certs I've added an example.
> Added example for custom claims

- Gopkg.lock
- ca/ca.go
- db/db.go
- db/db_test.go
* shutdown and reload database on SIGHUP
💔Thank you!
> Update nosql integration

- ca/ca.go
This PR updates CA properties on reload.
Fixes #71
> Update CA properties on reload.

- README.md
- docs/CONTRIBUTING.md
- docs/GETTING_STARTED.md
- docs/docker.md
- docs/provisioners.md
- docs/questions.md
Minor fixes I found in my travels.
> Bunch of typos and misformatting

- authority/provisioner/oidc.go
This PR adds the ability to check group membership inside OIDC provisioners.
By adding a `groups:['groupname']` declaration to the provisioner configuration, the validation code will check 
* if the received JWT token contains a `groups` claim
* if any of the provided group names is contained in such claim
Do note that `groups` is not a *standard* claim (as declared in https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), but nevertheless many providers support it (Azure, Auth0, Okta)
We have a setup where users are organized in groups, and we want to filter access to the CA.
We can not leverage domain filtering, since all users of the various groups have the same email domain. 
Ideally, we'd like to have a configurable mechanism which allows us to define (for each …
> Add option for checking group membership declared in JWT token

- Gopkg.lock
- authority/authorize_test.go
- authority/provisioner/jwk.go
- authority/provisioner/jwk_test.go
- authority/provisioner/sign_options.go
- authority/provisioner/sign_options_test.go
- ca/client.go
> Accept emails SANs

- authority/provisioner/aws.go
- authority/provisioner/aws_test.go
- authority/provisioner/azure.go
- authority/provisioner/azure_test.go
- authority/provisioner/gcp.go
- authority/provisioner/gcp_test.go
- authority/provisioner/jwk.go
- authority/provisioner/jwk_test.go
- authority/provisioner/oidc.go
- authority/provisioner/oidc_test.go
- authority/provisioner/sign_ssh_options.go
This PR implements a validator for SSH keys.
Fixes #100
> Implement validator for ssh keys

- .golangci.yml
- acme/authority.go
- acme/authz.go
- acme/directory_test.go
- api/revoke_test.go
- api/ssh_test.go
- authority/authority.go
- authority/db_test.go
- authority/provisioner/timeduration_test.go
- authority/tls.go
- ca/acmeClient_test.go
- ca/bootstrap_test.go
- ca/ca.go
- logging/responselogger.go
> Added a staticcheck and unused linters and trying to clear up new errors

- authority/authority.go
- authority/provisioner/jwk.go
- authority/provisioner/oidc.go
- authority/provisioner/oidc_test.go
- authority/provisioner/provisioner.go
- authority/provisioner/provisioner_test.go
- authority/provisioner/sign_ssh_options.go
- authority/provisioner/x5c.go
- authority/provisioner/x5c_test.go
> Instrument getIdentity func for OIDC ssh provisioner

- api/ssh.go
- authority/authority.go
- authority/options.go
- authority/ssh.go
- ca/client.go
- go.mod
> Expired cert

- acme/order.go
- acme/order_test.go
The ACME [RFC8555](https://tools.ietf.org/html/rfc8555) allows the CSR with DNS names only in the CommonName part of the subject:
```
The CSR MUST indicate the exact same set of requested identifiers as the initial
newOrder request. Identifiers of type "dns" MUST appear either in the commonName
portion of the requested subject name or in an extensionRequest attribute
[RFC2985] requesting a subjectAltName extension, or both.
```
> Allow DNS names in CommonName for ACME

- acme/api/account.go
- acme/api/account_test.go
- acme/api/handler_test.go
- acme/api/middleware_test.go
- acme/api/order_test.go
- acme/errors.go
> Should be returning status code 400 for ACME Account Not Found.

- README.md
Thanks good product.
I tried one by one and found miss command indicaton about help.
> Fix help command indication

- cmd/step-ca/main.go
- commands/app.go
Implementation of the feature requested in #171.
> Added Resolver Option

- templates/templates.go
- templates/templates_test.go
Add support for creating a new authority with templates, but without using the filesystem.
> Templates without the filesystem

- Makefile
- cmd/step-cloudkms-init/main.go
- docs/kms.md
This PR adds a new tool that allows initializing a PKI using Cloud KMS.
This tool is currently independent, but at some point, it should be integrated into `step ca init`
> Cloudkms init

- kms/cloudkms/cloudkms.go
- kms/cloudkms/cloudkms_test.go
On HSM keys are not generated instantly and the GetPublicKey fails
with a FailedPrecondition error. This change will retry GetPublicKey
if this happens.
> Retry CloudKMS GetPublicKey

- api/ssh.go
- authority/provisioner/sign_options.go
- authority/tls.go
- authority/tls_test.go
This PR enforce the same duration of the SSH certificates in the identity certificates.
> Enforce a duration for identity certificates

- authority/ssh_test.go
- authority/testdata/templates/config.tpl
- pki/templates.go
This PR removes from the template `ForwardAgent yes`.
> Do not enable by default ForwardAgent

- acme/api/account.go
- acme/api/account_test.go
> ACME accountUpdate ignore fields not recognized by the server.

- README.md
- docs/GETTING_STARTED.md
> Add RHEL/Centos install documentation and a section on systemctl configuration

- README.md
Documentation on how to do this on RHEL with some best practices.
💔Thank you!
> RHEL/CentOS Documentation

- docs/provisioners.md
Im tring provisioners, and found some docs miss part.
💔Thank you!
> docs: fix provisioner type

- README.md
Finally found the courage to begin gradually cleaning up the README. There will be more where this came from...
> First stab at a README update 😱

- README.md
- authority/provisioner/oidc.go
- docs/database.md
Rework for clarity and removal of a some things that don't seem to belong here. And, added emoji. 😬
> README updates, round 2

- authority/provisioner/aws.go
- authority/provisioner/aws_test.go
- authority/provisioner/utils_test.go
- go.mod
- go.sum
> AWS metadata service version tests

- pki/pki.go
> Add SSHPOP default provisioner if SSH enabled during init

- Makefile
- make/docker.mk
> introduce docker-buildx

- acme/api/handler.go
- acme/api/handler_test.go
- api/api.go
- api/rekey.go
- api/renew.go
- api/revoke.go
- api/sign.go
> Add cert logging for acme/certificate api

- README.md
This small pr fixes the step cli tool url.
> README: Fix url to step cli tool

- authority/provisioner/collection.go
> Standardize k8ssa check on issuer name

- errs/error.go
> Fix error message of bad request

- cmd/step-yubikey-init/main.go
- kms/apiv1/options.go
- kms/yubikey/yubikey.go
With this PR the default management key is not required as the user is able to set its own.
Fixes #323
> Make the YubiKey management key configurable.

- authority/authorize.go
- authority/authorize_test.go
We've found some OIDC tokens without a `nonce`, a `nonce` is currently used as token identifier to detect used tokens. This PR will check for empty values, and use a SHA256 of the if the provisioner returned token id is empty.
Fixes #373
> Create a hash of a token if a token id is empty.

- acme/authority_test.go
- acme/challenge.go
- acme/challenge_test.go
> Fix broken ValidateChallenge test

- systemd/README.md
- systemd/cert-renewer@.service
- systemd/cert-renewer@.timer
- systemd/step-ca.service
This PR includes the main service unit `step-ca.service`, and the service templates for the renewal service & timer.
> Add systemd files

- go.mod
- kms/awskms/awskms.go
- kms/awskms/awskms_test.go
- kms/cloudkms/cloudkms.go
- kms/cloudkms/cloudkms_test.go
- kms/yubikey/yubikey.go
This PR adds support to configure cloudkms, awskms, and YubiKey using a URI.
> KMS URI configuration

- README.md
- docs/CONTRIBUTING.md
Also updated contributor's guide to link to GH Discussions and Gitter
> Update "build from source" instructions

- authority/ssh_test.go
- authority/testdata/templates/sshd_config.tpl
- templates/values.go
Update sshd_config.tpl to a Match all block.
Fixes #479
> Update sshd_config.tpl to a Match all block.

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- debian/rules
> Move golangci-lint to github action and fix debian build action

- acme/api/account.go
- acme/api/handler.go
- acme/api/linker.go
- acme/api/linker_test.go
- acme/api/middleware.go
- acme/api/middleware_test.go
- acme/api/order.go
- ca/ca.go
> Use different method for unescpaed paths for the router

- Makefile
> VERSION from ENV should always take precedence over CI tags

- authority/tls.go
- ca/client.go
- ca/client_test.go
This PR adds an optional extension to the `db.AuthDB` interface to be able to store on renews and rekeys the old certificate. It also includes the implementation of the missing `client.Rekey`.
Fixes #315
> Renew DB interface and Rekey

- authority/config.go
- ca/identity/identity.go
> Init config on load | Add wrapper for cli

- api/api.go
- api/api_test.go
- ca/tls.go
This PR adds support for Ed25519 keys in a couple of places where it was missing.
> Ed25519 improvements

- cmd/step-pkcs11-init/main.go
> Allow configuration of PKCS11 subject name

- docs/CONTRIBUTING.md
- docs/revocation.md
Updating gitter link with new discord link
💔Thank you!
> update gitter to discord

- systemd/cert-renewer@.service
I broke the renewal condition with my previous PR 🥺 
So, this fixes it. (And I actually tested it this time.)
> Fix needs-renewal condition and switch to using ExecCondition

- scripts/README.md
- scripts/install-step-ra.sh
See also: https://www.notion.so/smallstep/Use-ACME-with-Certificate-Manage-3add740028fe49569ce9c4a9f28291ce
> RA install script

- api/api.go
- api/revoke.go
- api/sign.go
- api/ssh.go
- api/sshRekey.go
- api/sshRenew.go
- api/sshRevoke.go
- authority/provisioner/sign_options.go
- authority/provisioner/sign_options_test.go
- authority/provisioner/sign_ssh_options.go
- authority/provisioner/sign_ssh_options_test.go
- authority/ssh.go
- authority/tls.go
- authority/tls_test.go
- ca/ca_test.go
- errs/error.go
This PR adds support for sending forbidden errors to the cli. It also changes the TLS and SSH sign options to return always HTTP errors.
> Forbidden errors and more

- ca/acmeClient.go
- ca/acmeClient_test.go
This PR sets the Step CLI User-Agent generated at build time when performing ACME requests.
> Set Step CLI User-Agent when performing ACME requests

- examples/ansible/smallstep-certs/defaults/main.yml
- examples/ansible/smallstep-certs/tasks/main.yml
- examples/ansible/smallstep-install/defaults/main.yml
- examples/ansible/smallstep-install/tasks/main.yml
- examples/ansible/smallstep-ssh/defaults/main.yml
- examples/ansible/smallstep-ssh/tasks/main.yml
We have had some customers ask and others provide ansible configuration files. These are some examples of this that we can add to our Secret Menu.
> Added some example ansible configs

- CHANGELOG.md
This PR adds an entry to the changelog related to changes introduced in PR #827
> Add support for `AuthorizationCrt` in changelog.

- CHANGELOG.md
- authority/provisioner/azure.go
This PR adds an entry in the changelog for the PR #829
> Changeling PR 829

- CHANGELOG.md
- go.mod
- go.sum
This PR upgrades the nosql package, the new version allows filtering out database drivers using Go tags.
> Upgrade nosql package

- .goreleaser.yml
> Add armv5 build to GoReleaser configuration

- cmd/step-ca/main.go
- commands/app.go
This PR adds the `context` flag to `step-ca`.
Closes #802.
> add --context flag to step-ca command

- ca/renew.go
This change attempts to fix the test TestBootstrapClientServerRotation.Due to the backdate, the renewal options get too large, causing continuous renewals, and random errors. After experimenting with different options, truncating durations to seconds has shown better results than rounding or just using the plain time.
> Attempt to fix TestBootstrapClientServerRotation

- CHANGELOG.md
- go.mod
- go.sum
This PR upgrades go.step.sm/crypto
> Upgrade go.step.sm/crypto

- acme/challenge.go
- acme/challenge_test.go
> Fix ACME IPv6 HTTP-01 challenges

- CHANGELOG.md
- authority/config/config.go
- authority/provisioner/claims.go
- authority/provisioner/controller.go
- authority/provisioner/controller_test.go
- authority/provisioner/utils_test.go
- authority/provisioners.go
- go.mod
- go.sum
This PR renames the unreleased claim `allowRenewAfterExpiry` to `allowRenewalAfterExpiry` for consistency.
> Rename unreleased claim to allowRenewalAfterExpiry for consistency.

- ca/ca.go
> Cosmetic fix for consistency in the startup messages

- authority/provisioner/controller.go
When a client provides an expired certificate and `AllowAfterExpiry`
is not enabled, the client would get a rather generic error with
instructions to view the CA logs. Viewing the CA logs can be done
when running `step-ca`, but they can't be accessed easily in the
hosted solution.
This commit returns a slightly more informational message to the
client in this specific situation.
Improve error message when client renews with expired certificate
Generic error messages on the CLI when renewing a cert that is expired
> Improve error message when client renews with expired certificate

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- authority/admin/db.go
- authority/admins.go
- authority/authority.go
- authority/options.go
- authority/provisioners.go
- ca/adminClient.go
- ca/client.go
- docs/GETTING_STARTED.md
Need to expose some more inner workings of the Authority type for access from the cli.
Accompanying cli PR: https://github.com/smallstep/cli/pull/673.
> exposing authority configuration for provisioner cli commands

- cmd/step-pkcs11-init/main.go
pin-file support for step-pkcs11-init.
This allows the pin to be provided with bash redirection `<(curl path to secret)`
Pin passwords are private.
💔Thank you!
> step-pkcs11-init pin-file support

- authority/authority.go
- authority/linkedca.go
- authority/provisioner/jwk.go
- authority/provisioner/provisioner.go
- authority/provisioner/x5c.go
- authority/tls.go
- ca/ca.go
- cas/apiv1/options.go
- cas/apiv1/requests.go
- cas/stepcas/issuer.go
- cas/stepcas/issuer_test.go
- cas/stepcas/jwk_issuer.go
- cas/stepcas/jwk_issuer_test.go
- cas/stepcas/stepcas.go
- cas/stepcas/stepcas_test.go
- cas/stepcas/x5c_issuer.go
- cas/stepcas/x5c_issuer_test.go
- go.mod
- go.sum
This PR makes available to the DB interface the original authority used by an RA.
**TODO**:
> RA provisioner IDs

- CHANGELOG.md
- api/revoke.go
- api/revoke_test.go
> Validate revocation serial number

- authority/linkedca.go
- authority/provisioner/provisioner.go
- authority/tls.go
- cas/apiv1/requests.go
- cas/stepcas/issuer.go
- cas/stepcas/issuer_test.go
- cas/stepcas/jwk_issuer_test.go
- cas/stepcas/stepcas.go
- cas/stepcas/stepcas_test.go
- cas/stepcas/x5c_issuer_test.go
- go.mod
- go.sum
When an RA is used, this PR sends an endpoint ID to the CA so it can group the certs for the RA itself.
> Endpoint ID

- .gitignore
- acme/api/account_test.go
- acme/challenge.go
- acme/common.go
- authority/provisioner/acme.go
- authority/provisioner/acme_test.go
- authority/provisioners.go
- go.mod
- go.sum
This PRs adds AttestationFormats to the ACME provisioner to enable only specific attestation statement formats.
Depends on:
> Attestation Formats

- cmd/step-ca/main.go
This PR adds support for prompting key passwords with https://github.com/smallstep/crypto/pull/75 merged.
> Support to ask for key password after crypto change

- CHANGELOG.md
This PR adds to the changeling the new support for name constraints.
> Add name constraints support to changelog

- acme/challenge.go
- acme/challenge_test.go
This PR sets ValidatedAt when a challenge status is set to invalid.
> Set Challenge ValidateAt

- acme/challenge.go
- acme/challenge_test.go
- acme/errors.go
This PR reverts #1087 and adds a missing case in the acme errors switch.
> Revert ValidatedAt

- .github/workflows/release.yml
- .goreleaser.yml
> [action] updates and first pass at goreleaser deb

- authority/linkedca.go
- authority/provisioners.go
- authority/tls.go
- authority/tls_test.go
- go.mod
- go.sum
This PR adds support for sending the attestation data on a linkedca and storing it in the database if it gets implemented.
> Attestation data

- docs/README.md
@tashian if this looks good to you, go ahead and merge.
> Update revocation docs link

- commands/app.go
This PR changes the new step-ca flags to use a standard style.
> Use the same style of flags

- commands/app.go
It creates a new context with the given name if the flags --token and --context are passed, and the context does not exist.
Fixes #1047
> Create context for automatic RAs

- CHANGELOG.md
This PR adds missing changes in the changelog and prepares it for the v0.23.0 release.
> Prepare changelog for v0.23.0 release

- api/log/log.go
- api/log/log_test.go
This PR merges `log.Error` tests.
> Merge log.Error tests

- CHANGELOG.md
This PR prepares the changelog to release v0.23.1
> Upgrade changelog for v0.23.1

- CHANGELOG.md
This PR adds to the changelog the most important changes in v0.23.2
> Add changelog for v0.23.2

- CHANGELOG.md
This PR adds the changes of v0.24.0 to the changelog.
> Add changelog for v0.24.0

- go.mod
- go.sum
This PR upgrades go.step.sm/crypto with the new version of azidentity.
> Upgrade go.step.sm/crypto 

- CHANGELOG.md
Added v0.24.2 and v0.24.1. 
Day of release needs to be updated.
> Update changelog for v0.24.2 release

- pki/helm.go
This PR fixes the use of tabs instead of spaces in the helm template.
> Fix tabs instead of spaces in helm chart

- authority/provisioner/aws.go
This PR fixes the linter errors from #1404
> Fix linter errors from #1404

- acme/account.go
- acme/account_test.go
- acme/api/account.go
- acme/api/middleware.go
- acme/api/middleware_test.go
- acme/db.go
- acme/db/nosql/account.go
- acme/db/nosql/account_test.go
> Store and verify Acme account location 

- .goreleaser.yml
https://github.com/smallstep/certificates/releases/tag/v0.24.3-rc.2
https://github.com/smallstep/certificates/actions/runs/5273634613/jobs/9537338652
> Add unversioned filenames to GitHub assets

- ca/tls_test.go
> chore: log error

- scripts/badger-migration/main.go
This commit adds an option that runs the migration on a virtual database that doesn't do anything. This option can be used to see how many rows there are.
> Add option to dry-run the migration

- api/api.go
- api/api_test.go
- api/models/scep.go
- authority/provisioner/scep.go
- authority/provisioners.go
This PR changes the type of the decrypter key password to string to be consistent with other passwords in the ca.json
> Change scep password type to string

- .goreleaser.yml
> Fix cosign identity regexp

- README.md
Fix link in README
Contribution Guide is easier to find
> Amend link to Contribution Guide in README

- cas/stepcas/stepcas.go
- cas/stepcas/stepcas_test.go
This commit updates the RA token to use the SANs coming from the template instead of the CSR.
Note that this PR might break some admin tokens. This PR should fix the problem:
> Build RA token using SANs from the template

- authority/authority.go
- authority/meter.go
- internal/metrix/meter.go
This PR adds KMS-related instrumentation.
> KMS instrumentation

- authority/ssh.go
- authority/tls.go
This PR split the main metered methods in two to make it harder to miss metrics in the future.
> Split metered functions

- scripts/install-step-ra.sh
- use scarf links
- update code to reflect new internal package structure
> Update RA installer step-ca package URL

- go.mod
- go.sum
Fixes CI not passing on https://github.com/jackc/pgx/security/advisories/GHSA-mrww-27vc-gghv / https://github.com/jackc/pgx/security/advisories/GHSA-m7wr-2xf7-cm9p
> Upgrade `pgx` to `v4.18.3`

- acme/challenge.go
- acme/common.go
- acme/order.go
- api/models/scep.go
- authority/admin/api/policy.go
- authority/provisioner/provisioner.go
fix function names in comment 
💔Thank you!
> chore: fix function names in comment

- Makefile
> Change `make install` path

- templates/values.go
This commit updates the SSH template step_config.tpl. This new version allows to run `step ssh proxycommand` with a `--console` flag that will execute the OIDC flow using the Device authorization grant flow.
> Update step_config.tpl template

- .github/ISSUE_TEMPLATE/config.yml
Small PR - PR #1166 moved the location of the `CONTRIBUTING.md`. This PR adjusts sources to changes.
> Update reference to contributing file

- docker/Dockerfile.hsm
This adds in PKCS11 related packages to help with interfacing with PKCS11 HSM easier.
> Add PKCS11 Packages in HSM container image

- authority/provisioner/controller.go
- authority/provisioner/controller_test.go
This commit moves the wrap transport initialization to the controller constructor.
> Move wrap transport initialization to constructor

- acme/challenge.go
- acme/challenge_test.go
This commit adds the format of the payload to the challenge object.
> Add attestation format to challenge

- .goreleaser.yml
> Fix cosign cert filename in verify instructions

- ca/ca.go
This PR refactors the code to shutdown the services concurrently and return the first error instead of doing that sequentially.
> Use errgroup to shutdown services concurrently.
