ca/bootstrap.go
ca/bootstrap_test.go
examples/README.md
examples/bootstrap-client/client.go
examples/bootstrap-server/server.go

This PR allows to pass a context to cancel the renewal goroutines when the BootstrapServer and BootstrapClient are used.

Add context to bootstrap methods

---

ca/bootstrap.go
ca/bootstrap_test.go
ca/tls.go
ca/tls_test.go
examples/README.md
examples/bootstrap-mtls-server/server.go

This PR adds new helpers in the SDK to add direct support for mTLS. It adds a new method Client. GetServerMutualTLSConfig that configures the ClientAuth to tls.RequireAndVerifyClientCert instead of tls.VerifyClientCertIfGiven, and a new function BootstrapServerWithMTLS, that uses the previous function to configure an http.Server.
This PR also adds a new example using BootstrapServerWithMTLS.
Open questions: should we use mTLS by default, and with by default I mean with the shorter/nice function names (BootstrapServer, GetServerTLSConfig)?

Add helpers to add direct support for mTLS.

---

ca/ca.go
ca/renew.go

Force the renew of the CA server cert if it's about to expire. This only happens after a wake up after a hibernation if enough time has passed to expire the certificate.
This PR only solves the problem for the CA server and not server or clients using CA certificates, as those won't be able to use TLS requests with expired certs.

Force the renew of the CA server.

---

authority/authority.go
authority/authority_test.go
authority/authorize.go
authority/authorize_test.go
authority/config.go
authority/config_test.go

Accept as a valid audience the URL without the port, even if it's not the port 443. Fixes #17.
There're no changes required in [smallstep/cli](https://github.com/smallstep/cli). In fact, the audience set in the token must be an URL accessible, as it's required to get the root certificate.

Do not require the port in the audience check.

---

authority/provisioners.go

In Go, len returns signed ints, not unsigned ints; consequently, this code
comparison overflows on 32-bit systems, like ARM.

authority/provisioners: fix overflow on 32-bit systems

---

ca/bootstrap.go
ca/bootstrap_test.go
ca/client.go
ca/mutable_tls_config.go
ca/tls.go
ca/tls_options.go
ca/tls_options_test.go

Certificate pools should be safely updated when root or federation certificates are rotated. A server uses `tls.Config.GetConfigForClient` to provide the refreshed version of the tls.Config while clients use a custom http.Transport.DialTLS that uses the refreshed tls.Config. Fixes #23
This PR also adds the method `BootstrapListener` that creates a `net.Listener` configured with the TLS certificate provided by the CA

SDK should update certificate pools safely

---

Gopkg.lock
authority/tls.go
authority/tls_test.go

Extensions were not properly copied on renew. In particular, the extensions that we add were not appearing, the rest of them are added by Go if they are not provided.
Fixes #36

Fix renew extensions

---

api/api.go
api/api_test.go

This PR adds some extra information in the logs for `/sign` and `/renew` endpoints.
The ott is included in the `/sign` and the raw certificate and some certificate properties are included in both endpoints.

Add certificate information to logs

---

authority/config.go
authority/config_test.go
authority/provisioner/claims.go
authority/provisioner/jwk.go
authority/provisioner/jwk_test.go
authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/utils_test.go

In a "/provisioners" request to the CA, each provisioner shows a `"claims": {}` element even if they are only using the default one.
This PR splits the claims model and the claims methods so the `omitempty` tag works properly.

Proper omitempty on claims

---

api/api.go
api/api_test.go
authority/provisioner/sign_options.go
authority/provisioner/timeduration.go
authority/provisioner/timeduration_test.go
authority/tls_test.go
ca/ca_test.go
ca/client_test.go
ca/tls_test.go

This PR adds support for the new type `TimeDuration` that allows the use of RFC3339 time formatted timestamps or time.Duration strings.
Fixes smallstep/cli#60

TimeDuration support in sign requests.

---

Gopkg.lock
Gopkg.toml
authority/tls.go
authority/tls_test.go

This PR uses the new x509util library that uses standard x509 for creating certificates. It also puts in the right place the validation of certificates.

Use standard x509 creating signed certificates

---

autocert/controller/main.go
autocert/controller/main_test.go
autocert/install/02-autocert.yaml

I would like to prevent pods in one namespace from minting certificates for another namespace.
This seems like a decent approach, but thought I'd open the PR to get feedback.

Do not allow pods in one namespace to create certificates for hostnames from another namespace.

---

Gopkg.lock
Gopkg.toml
authority/authorize.go

This PR adapts certificates code to go-jose@2.3.0, claims `iat`, `nbf`, and `exp` are now pointers instead of values. 
~This PR won't be merged until square/go-jose#224 gets merged~. Instead of waiting for the merge we are using our fork.
Related to smallstep/cli#105

Update go jose

---

autocert/install/02-autocert.yaml

Change default to false until we have more elaborate documentation plus verification hook to bubble errors up to kubectl.
Consider switching default back on once these issues are resolved:
* https://github.com/smallstep/certificates/issues/61
* https://github.com/smallstep/certificates/issues/62

Flip default for certificate restriction to namespace to false

---

authority/authority.go
authority/authority_test.go
ca/bootstrap_test.go
ca/ca.go

This PR only allows reloading the CA configuration if the database configuration hasn't changed, or is new. This avoids the stop of the server if something goes wrong.
Fixes #smallstep/ca-component#170

Do not allow reload with database configuration changes.

---

Gopkg.lock
ca/client.go
ca/client_test.go
ca/provisioner.go
ca/provisioner_test.go

The type `ca.Provisioner` is used by some projects to generate tokens for a JWK provisioner. This PR adds some flexibility in the construction so it does depends on files, and []byte can be used to set the root CA.

Improve ca.Provisioner

---

authority/provisioner/keystore.go
authority/provisioner/keystore_test.go
authority/provisioner/utils_test.go

This PR fixes a panic when the Cache-Control header has a max-age of 0.
Fixes #81

Fix panic when max-age is set to zero.

---

Gopkg.lock
authority/provisioner/aws.go
authority/provisioner/aws_test.go
authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/gcp.go
authority/provisioner/gcp_test.go
authority/provisioner/sign_options.go
authority/provisioner/sign_options_test.go
authority/provisioner/timeduration.go
authority/provisioner/utils_test.go

This PR allows custom common names in cloud identity provisioners. It also extends the x509 provisioner extension with optional data.
The previous version was forcing the common name to be the instance id or instance name. When disableCustomSANs is set to true, then we will enforce the common name but it will be a little bit more flexible:
* For AWS common name can be: instance id (i-1234...), private ip (172.31.23.47), or hostname (ip-172-31-23-47.zone.compute.internal)
* For GCP common name can be: intance id (1234), instance name (my-instance), or one of the two domain names (my-instance.c.my-project.internalor my-instance.zone.c.my-project.internal):
* For Azure the common name has to be the VM name, we don't have trusted access to anything else.
This will be accompanied by another PR …

Allow custom common names in cloud identity provisioners

---

Gopkg.lock
authority/provisioner/provisioner.go

Compiled clients like `step` will fail if we add a new provisioner type and the version `step` is compiled does not supports it. This PR changes the behavior and skips unknown provisioners instead of failing.
The main 'problem' of this change is that step-ca is not able to detect invalid provisioners, this can also be a feature as the same configuration can be used by different versions.

Skip unsupported provisioners.

---

authority/provisioner/sign_ssh_options.go

This PR truncate to seconds ValidAfter if it's generated in step-certificates. Truncating avoids that the certs are not yet valid if they are immediately used.

Truncate to seconds ValidAfter

---

authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/utils_test.go
docs/provisioners.md

This PR adds support for a `listenAddress` property in the OIDC provisioners that allows defining a fixed port for those OIDC providers that don't support a random port, like Okta or Auth0.
Fixes smallstep/cli#150

Address support on OIDC provisioners

---

docs/acme.md

Small markdown formatting fix to the ACME documentation page. Please close if intentional/you'd rather fix yourselves.
Thanks!

Fix formatting around step certificate install link

---

Gopkg.lock
acme/api/handler_test.go
acme/authority.go
acme/authority_test.go
acme/common.go
ca/ca.go

@maraino Thoughts on making this change? Didn't realize that `-`s were special / illegal characters in table names. This change won't break existing operation, but people using the badger DB will have a bunch of "tables" (really just keys) that won't be used anymore.

Create ACME database tables when initializing ACME autority.

---

acme/common.go
acme/order.go
acme/order_test.go
api/api.go
api/api_test.go
authority/tls.go
authority/tls_test.go
ca/bootstrap_test.go
ca/client_test.go
ca/tls_test.go
docs/GETTING_STARTED.md

- Functions Authority.Sign, Authority.Renew returns certificate chain instead of 2 members.
- Extends SignResponse about CertChainPEM.
Implements #126
💔Thank you!

Change api of functions Authority.Sign, Authority.Renew

---

README.md

Following the README procedure to install the Debian packages, I figured out that the links were broken.

Fix Debian package link and version in README

---

acme/challenge.go
acme/challenge_test.go

Perform domain normalization for wildcard domains, so we do query
TXT records for _acme-challenge.example.domain instead of
_acme-challenge.*.example.domain when performing DNS-01 challenge. In
this way the behavior is consistent with letsencrypt and records queried
are in sync with the ones that are shown in certbot manual mode.

Perform domain normalization for wildcard domains

---

docs/questions.md

This addresses issue #160 
I extended @mmalone's example a bit and added it to the FAQ.
In addition to Mike's directions for AD CS, I added directions for AWS private CA, CFSSL, and OpenSSL.
Some small lingering questions:
The AD CS directions were confirmed by some folks in #160

Update FAQ: "I already have PKI"

---

.travis.yml
authority/provisioner/aws.go
authority/provisioner/aws_test.go
authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/gcp.go
authority/provisioner/gcp_test.go
ca/tls.go
go.sum

This PR adds support for custom SSH principals on cloud identity provisioners.
It also upgrades builds to use Go 1.14 and fix a lint error.

Allow custom principals on cloud identity provisioners

---

api/api_test.go
api/ssh.go
api/sshRekey.go
api/sshRenew.go
api/sshRevoke.go
api/ssh_test.go
authority/authority.go
authority/options.go
authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/provisioner.go
authority/provisioner/provisioner_test.go
authority/ssh.go
authority/ssh_test.go

This PR Adds a `context.Context` to all the SSH methods.

Add context to ssh methods

---

.travis.yml
ca/tls.go

Use go 1.13 to build certificates, tests are probably hanging due to https://github.com/golang/go/issues/38023

Use go 1.13 to build certificates

---

api/ssh_test.go
sshutil/types.go

Tags are more flexible and what we use in the managed offering.

ssh/api: Use host tags instead of groups

---

authority/provisioner/sign_options.go
authority/provisioner/sign_options_test.go

This PR removes the requirement for a certificate request to have a common name. Certificate requests will be accepted if the common name matches the token subject or the common name is empty.
Fixes #226

Remove the requirement for CSR to have a common name

---

pki/pki.go

If a root certificate is provided to init an authority the fingerprint is not currently stored in the default.json file. This patch simply stores the fingerprint of the supplied certificate.
For example
./step ca init --name="test" --dns="b.ca" --address=":443" --provisioner=a@b.ca --root=root-ca.crt --key=root-ca.key
Copying root certificate...
all done!
Generating intermediate certificate...
all done!
✔ Root certificate: /home/dev/.step/certs/root_ca.crt
✔ Root private key: /home/dev/.step/secrets/root_ca_key
✔ Root fingerprint:
✔ Intermediate certificate: /home/dev/.step/certs/intermediate_ca.crt
✔ Intermediate private key: /home/dev/.step/secrets/intermediate_ca_key
✔ Database folder: /home/dev/.step/db
✔ Default configuration: /home/dev/.step/config/defaults.json
✔ Certificate …

Add root fingerprint to pki if certificate given

---

api/ssh.go
authority/ssh.go
authority/ssh_test.go

OIDC provisioners create an SSH certificate with two principals. This
was avoiding the creation of user provisioner certificates for those
provisioners.
Fixes smallstep/cli#268

Add support for user provisioner certificates on OIDC provisioners.

---

authority/provisioner/azure.go
authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/utils_test.go

This PR adds an option to setup multi-tenant OIDC provisioners for Azure. Multi-tenant applications uses a common openid-configuration [1] where the issuer is formed replacing the string `{tenantid}` with the actual tenant.
[1] https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

Add support for multi-tenant OIDC provisioners

---

authority/authority.go
authority/authority_test.go
authority/config.go
authority/options.go

When the CA is embedded in a third party product like Caddy, the config needed to use placeholders to be valid. This change adds a new method `NewEmbeddedAuthority` that allows to create an authority with the given options, the minimum options are a root and intermediate certificate, and the intermediate key.
Fixes #218
@dopey Should I change the name to `authority.NewEmbedded()`, or do you have any other suggestions?

Create a method to initialize the authority without a config file

---

authority/authority.go
authority/authority_test.go
authority/config.go

This change is to make easier the use of embedded authorities. It can be difficult for third parties to know what fields are required. The new init methods will define the minimum usable configuration.

Initialize the required config fields on embedded authorities

---

acme/order.go
acme/order_test.go
authority/provisioner/acme.go
authority/provisioner/acme_test.go
authority/provisioner/sign_options.go
authority/provisioner/sign_options_test.go

As described in #259, some systems require certificate's Subject field to be non-empty. At the same time, `certbot` does not send CommonName in its certificate request. LetsEncrypt automatically generates CN for certificate based on the first SAN in the request. It is implemented under the `forceCN` config option.
This PR duplicates the described behavior for step-ca.
Closes #259

[Feature] Force CommonName for certificates from ACME provisioner

---

.travis.yml
Makefile
authority/authority.go
ca/renew.go
cmd/step-cloudkms-init/main.go
cmd/step-yubikey-init/main.go
docs/kms.md
go.mod
go.sum
kms/apiv1/options.go
kms/apiv1/registry.go
kms/apiv1/requests.go
kms/cloudkms/cloudkms.go
kms/kms.go
kms/softkms/softkms.go
kms/yubikey/yubikey.go
kms/yubikey/yubikey_no_cgo.go

This PR adds experimental support for YubiKey, currently, only TLS certificates are supported.
Yubikey support requires CGO and it's not going to be enabled on CI builds.
Yubikey uses [go-piv/piv-go](https://github.com/go-piv/piv-go), and it requires PCSC lite support, this is available by default in macOS and Windows systems, but not on Linux, see https://github.com/go-piv/piv-go#installation for installation instructions.

Yubikey support

---

acme/account_test.go
acme/api/handler_test.go
acme/api/middleware.go
acme/authority.go
acme/authority_test.go
acme/common.go
acme/order.go
acme/order_test.go
authority/provisioner/acme.go
ca/ca.go

According to the ACME spec (https://tools.ietf.org/html/rfc8555#section-7.1.3), ACME Order responses must contain the `notBefore` and `notAfter` attributes that will later be used to set the validity bounds on the certificate. If these values are not set as part of the NewOrder request `step-ca` does not set them in the Order object stored in the database (and returned to the user). This results in Order responses that have the `NotBefore` and `NotAfter` values set to the zero timestamp (e.g. `\"notAfter\":\"0001-01-01T00:00:00Z\"`). 
`step-ca` should set `notBefore` and `notAfter` at the time of order creation to the proper values based on the inputs and the ACME provisioner claims.

Set nbf and nbf for ACME orders even when they are not set in the request.

---

authority/provisioner/provisioner.go
authority/provisioner/provisioner_test.go

This PR will create principals with dot symbols in it when an OIDC provisioner is used. We are not changing the sanitation logic, we append the third principal if necessary:
This PR will create SSH certificates with the following principals:
```
firsstlast@example.com => ["firstlast", "firstlast@example.com"]
first.last@example.com => ["firstlast", "first.last", "first.last@example.com"]
FirstLast@example.com => ["firstlast", "FirstLlast@example.com"]
First.Last@example.com => ["firstlast", "First.Last", "First.Last@example.com"]
First+Last@example.com => ["first_last", "First+Last", "First+Last@example.com"]
```
Fixes #253, #254

Allow dots and other symbols in principals for OIDC

---

acme/api/handler.go
acme/errors.go

RFC 8555 § 7.3.5 is not listed as optional but we do not currently
support it. Rather than 404, return a 501 to inform clients that this
functionality is not yet implemented.
The notImplmented error type is not an official error registered in the
ietf:params:acme:error namespace, so prefix if with step:acme:error. An
ACME server is allowed to return other errors and clients should display
the message detail to users.
Fixes: https://github.com/smallstep/certificates/issues/209

acme: Return 501 for the key-change route

---

acme/account.go
acme/account_test.go
acme/authority.go
acme/authority_test.go
acme/order.go
acme/order_test.go

According to the ACME spec "pending orders SHOULD be returned by the `GetOrders` api".
Invalid orders SHOULD not be returned. Other states, are not discussed and are therefore not necessary to return.
The `acme_account_orders_index` is a table mapping accountID to a list of orders owned by that account. Currently the list of orders is never audited -- it continues to grow with each new order. Orders are never removed from this list. 
This PR "audits" the list of orders each time the list is requested by the API. Only orders in the PENDING state are left in the list. This "should" fix errors seen by users where the byte size of the row becomes too large for the database to write.
Closes #273

Only retain `pending' orders in the `acme_account_orders_index`

---

acme/account_test.go
acme/order.go
acme/order_test.go

`func save(bucket, key, old, newval []byte) error`
The orderIDs list can now have items removed from it. This is important because without this commit it was possible to save an empty list (`newval`) as the value of orderIDs (`json.Marshal([]string{})`). However, the value of `old` was always converted to `nil` if the `len(old) == 0`.  This would lead to a conflict where the actual `old` value in the db was an empty list, but the `save` method would always try to use `nil` as the comparator.
To "fix" this issue we'll make it impossible to store an empty list as the value for the orderIDs index. It will always be converted to `nil` if empty.

Always convert empty list to nil when saving orderIDs index.

---

cmd/step-ca/main.go
cmd/step-yubikey-init/main.go
kms/kms.go

This PR moves the import of kms packages to the main package. With this, packages that import the authority won't load by default all the supported kms with all its dependencies.
Fixes #228

Move load of kms to main package.

---

authority/ssh.go
authority/ssh_test.go

This PR returns an error if we try to get the ssh configuration if the ca doesn't define templates.
Fixes #289

Avoid nil pointer panic on step ssh config with no templates.

---

authority/authority.go
authority/ssh.go
authority/ssh_test.go
authority/testdata/templates/fail.tpl
pki/templates.go
templates/templates.go
templates/templates_test.go
templates/values.go
templates/values_test.go

This PR adds support for checking template variables, to avoid `<no value>` in templates causing bad configuration.
Currently only the default `sshd_config.tpl` template requires user variables, the required variables are set in the ca.json, but the CA can backfill those values if the default template is used. Users configuring their own templates can either check the required values on the template or configure the required values in the ca.json.
With this change if we run `step` without the required variables we will see the following error:
```sh
$ step ssh config --host
required variable 'Certificate' is missing, please use `--set <key=value>` flag
Re-run with STEPDEBUG=1 for more info.
```
Fixes https://github.com/smallstep/cli/issues/232

Add support for required template variables

---

authority/ssh.go
authority/ssh_test.go

This PR does not return a bastion for the bastion configured, avoiding this way infinite loops. Although not a perfect solution, because a bastion can have different names, as we cannot guarantee that the client and CA are in the same network, the simple solution is in some cases the safest. 
Fixes #296

Do not return bastion for the configured bastion host.

---

examples/README.md
examples/docker/Makefile

This fixes #295, which was caused by libc incompatibility between the host OS and Alpine.
Tested on Ubuntu and macOS.

Fix Docker example build on Linux

---

docs/GETTING_STARTED.md

_superseding https://github.com/smallstep/certificates/pull/316_
1. The user (and optionally the group) should be the same as the one create in line 212 (`$ useradd step`)
2. Since the service unit name is `step-ca` and the program it uses is also called `step-ca`, the directory to store the logs should also be called `step-ca` imo.
3. Fixed the name of the service in line 246 (`$ systemctl start smallstep`): There's no service called `smallstep`.

Getting Started docs fixes

---

Makefile

Note: Github assets will convert `~` to `.` in the deb pkg name when travis uploads the assets.
Fixes #261

Convert '-' to '~' in deb package name

---

.travis.yml
debian/changelog
make/docker.mk

Just a couple cleanups here:
- Upgrade Travis VM to Ubuntu 20.04 — which comes with Docker 19.03
- Fix `.travis.yml` based on their linter's recommendations
- `docker/binfmt` is now 'linuxkit/binfmt`
- Docker 19.03: use `docker buildx` subcommand instead of calling `docker-buildx` directly

Small changes to docker/travis

---

.dockerignore
docker/Dockerfile.step-ca

- Use `COPY` instead of `ADD`, because `ADD` does Magical Things that we don't need (like auto-ungzipping)
- Use `WORKDIR` instead of `RUN mkdir`
- Added a `.dockerignore` file to reduce the build context size
- Added a `HEALTHCHECK` for the CA (runs every 30 seconds and reports health status in `docker ps`)
- The `CMD exec` is already a [shell form `CMD`](https://docs.docker.com/engine/reference/builder/#cmd), so it doesn't need `/bin/sh -c` (which ends up being redundant). I tested that `docker kill -s HUP` still works properly.
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Update Dockerfile.step-ca to match best practices

---

go.mod
kms/yubikey/yubikey.go

With piv-go 1.5.0, the lib tries to use the yubikey attestation certificate to guess the PIN policy, which seems quite crazy.
Attestation certificate can be found on yubikey only in the case of yubikey-self-generated private key. In our use case we do have an external-generated key we want to back up and carefully import on the yubikey, so we don't have the attestation certificate.
This PR transmits the PINPolicy "always" to the piv-go pkg to make it clear we have the PIN and don't want the lib to guess the PINPolicy value. This option is introduced in piv-go 1.6.0.
It solves the use of the Yubikey key storage with externally generated keys.
See : https://github.com/go-piv/piv-go/blob/b3946de126a897b5129fef09d836e425cf1fc721/piv/key.go#L687
- transmits the PINPolicy "always" to the piv-go …

avoid using yubikey attestation cert

---

make/bundle.sh

This PR adds the missing step to add `step-awskms-init` to binary releases.
Fixes #332

Add step-awskms-init to the binary releases.

---

authority/provisioner/k8sSA.go
authority/provisioner/oidc.go
go.mod
go.sum

This change replaces the .Insecure.CR template to one that sets
all the SANs, but uses key usages and extended key usages for
regular TLS certificates.

Use new admin template for K8ssa and admin-OIDC provisioners.

---

authority/authority.go
authority/config.go
cas/apiv1/options.go
cas/apiv1/options_test.go
cas/cloudcas/cloudcas.go
cas/cloudcas/cloudcas_test.go
docs/cas.md
pki/pki.go

This PR adds support for CloudCAS in step ca init.

Add support for CloudCAS on step ca init

---

go.mod

While attempting to compile step-ca for my Raspberry Pi 3+ (armv7l, 32bit), I kept running into this error when compiling with `CGO_ENABLED=1` in the Makefile and env vars: `GOOS=linux`, `GOARCH=arm`:
```sh
$ make build GOFLAGS=""
github.com/go-piv/piv-go/piv
../../go/pkg/mod/github.com/go-piv/piv-go@v1.6.0/piv/pcsc_linux.go:29:12: constant 2148532270 overflows _Ctype_long
Makefile:83: recipe for target 'bin/step-ca' failed
make: *** [bin/step-ca] Error 2
```
Some quick Googling led me to [the pull request that fixes this](https://github.com/go-piv/piv-go/pull/81) and I saw that it was released in [v1.7.0](https://github.com/go-piv/piv-go/releases/tag/v1.7.0)
I'm a Golang newbie but it looks like simply bumping the `go-piv` dependency might be all that is required to get this fix into the …

Bump go-piv to v1.7.0 for x32 overflow fix

---

.travis.yml
Makefile
kms/pkcs11/other_test.go
kms/pkcs11/softhsm2_test.go
kms/pkcs11/yubihsm2_test.go

Do not require CGO (and dependencies like libpcsclite) when doing `make`, but require CGO for testing and linting in travis.
Fixes #471

Permit linting and testing without CGO support.

---

kms/cloudkms/cloudkms.go
kms/cloudkms/cloudkms_test.go
kms/cloudkms/signer.go
kms/cloudkms/signer_test.go

This PR refactors a little bit the crypto.Signer cloudkms to return an error on the constructor, we preload the public key on the constructor, so we can verify that it exists. We're doing the same thing in the awskms.
Fixes #487

CloudKMS signer with errors

---

.goreleaser.yml

This will need a little testing when we cut the next release.
Mariano merged the remaining issue that was making step-ca bork on Windows PowerShell.

Add step-ca Windows build & Scoop release to goreleaser

---

cmd/step-pkcs11-init/main.go

Adds a "pin" flag to cmd/step-pkcs11-init so that it can take it as input from another program

PKCS11 Init Pin Flag

---

ca/ca.go
cas/stepcas/issuer.go
cas/stepcas/issuer_test.go
cas/stepcas/jwk_issuer.go
cas/stepcas/jwk_issuer_test.go
cas/stepcas/stepcas.go
cas/stepcas/stepcas_test.go
cmd/step-ca/main.go
commands/app.go

This PR extends the StepCAS RA mode with the following improvements:
* Allow passing the issuer password using the flag `--issuer-password-file`. 
* Allow getting the JWK provisioner from the CA using  `GET /provisioners`. This way the JWK key is only held in memory.
Using the remote encrypted key one could run the following `ca.json` like `step-ca --issuer-password-file pass.txt ca.json`:
```
{
"address": ":9100",
"dnsNames": ["ra.smallstep.com"],
"db": {
"type": "badgerV2",
"dataSource": "/home/step/db"
},
"logger": {"format": "text"},
"authority": {
"type": "stepcas",
"certificateAuthority": "https://ca.smallstep.com:9000",
"certificateAuthorityFingerprint": "b4fc6b547ca4610b69cfcc53c6933e7a37170476dfe134a2c257726f92c403f5",
"certificateIssuer": {
"type": "jwk", 
"provisioner": …
```

RA mode improvements

---

logging/handler.go
logging/handler_test.go

When deployed and running in Kubernetes, step-ca will output a log statement every 5 seconds at INFO level from the ongoing readiness/liveness probe requests. This PR changes the behaviour so that successful kube-probe requests will only be logged at Trace level by default.
Fixes #420

Log successful kube-probe requests at Trace lvl

---

docs/provisioners.md

misspelling that is driving me nuts
💔Thank you!

Update a spelling error in provisioners.md

---

ca/client.go

This PR changes all the custom transports being used to add `Proxy: http.ProxyFromEnvironment`
Fixes #535

Always specify a Proxy in all custom transports.

---

acme/api/handler.go

This PR removes the replay nonce on get directory request. According to RFC 8555, the replay nonces are only required in POST requests. And of course in the new-nonce request.

Remove the creation on nonce on get acme directory

---

authority/tls.go

This PR adds a temporary solution to allow an extension of a `db.AuthDB` interface that logs the full chain of certificates instead of just the leaf.

Add extension of db.AuthDB to store the fullchain

---

ca/client.go
ca/identity/identity.go
ca/identity/identity_test.go
ca/identity/testdata/config/tunnel.json
ca/tls.go
ca/tls_test.go
kms/yubikey/yubikey.go

This PR adds experimental support for TLS over (m)TLS tunnel, this can be useful in configurations like:
```
step-ca (ra-mode) <--> ghostunnel server <--> step-ca
```
If the RA is started with the environment variable `STEP_TLS_TUNNEL=ghostunnel:9000` it will connect to ghostunnel server using as client certificate the identity certificates if available. And then it will talk HTTPS over that connection.
How to test it:
1. Start CA (ca.smallstep.com):
```sh
step-ca /etc/step-ca/ca.json
```
2. Create a certificate for ghostunnel:
```sh
step ca certificate ghostunnel.smallstep.com gt.crt gt.key
```
3. Start ghostunnel server (ghostunnel.smallstep.com)
```sh
ghostunnel server --cert gt.crt --key gt.key --cacert root_ca.crt \
--listen :9000 --target ca.smallstep.com:9000 --allow-cn …
```

Add experimental support for a TLS over TLS tunnel.

---

cmd/step-pkcs11-init/main.go

Configurable pkcs11-init output paths

---

cmd/step-pkcs11-init/main.go

Originally `pin-source` would be read twice, once by `u.Pin()` and again inside `kms.New()`. 
This double read is problematic when reading pins from FIFO pipes. 
This PR fixes this by removing the double read.

Allow reading pin from kms string

---

api/api.go

The provisioner name was printed as a byte slice due to a regression. This PR prints it as a string again when logging a certificate.
💔Thank you!

Fix logging provisioner name as string

---

api/api.go

Using a JSON string fixes a common issue with JSON parsers that
deserialize all numbers to a 64-bit IEEE-754 floats. (Certificate
serial numbers are usually 128 bit values.)
This change is consistent with existing log entries for revocation
requests.
See also: #630, #631
💔Thank you!

Log certificate's serial number as stringified decimal number

---

authority/authorize.go
authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/provisioner.go
authority/tls.go

This PR allows the reuse of Azure tokens if DisableTrustOnFirstUse is true
Azure caches a token for up to 24h, and we cannot issue a new certificate for the same instance in that period of time.
The meaning of this parameter is to allow the signing of multiple certificates in one instance. This is possible in GCP, because we get a new token, and is possible in AWS because we can generate a new one. On Azure, there was no other way to do it unless you wait for 24h.
Fixes #656

Allow the reuse of azure tokens if DisableTrustOnFirstUse is true

---

acme/challenge.go
acme/challenge_test.go
kms/uri/uri.go
kms/uri/uri_test.go

This PR fixes step-ca compatibility issues with Go 1.17. Compatibility changes are:
* Go 1.17 introduces a change in the net/url package disallowing the use of a semicolon (;) in URL queries. We used `url.ParseQuery` to decode the opaque string that is semicolon-separated. Now before decoding the opaque string we replace the semicolon with an ampersand. See https://golang.org/doc/go1.17#semicolons
* In Go 1.17 `tls.Dial` will fail if client and server configured protocols do not overlap. See https://golang.org/doc/go1.17#ALPN. The ALPN challenge tests that check that the negotiated protocol is `acme-tls/1` were failing because of this.  This change detects the error `no_application_protocol (120)` and fails as it was failing before.
* There's a change in the error message on one test …

Go 1.17 compatibility

---

docker/Dockerfile.step-ca
docker/entrypoint.sh

The goal of this PR is to simplify the CA init process with Docker, using environment variables.
See [this Notion page](https://www.notion.so/smallstep/new-docker-readme-7b2af4d61c324803bb01f2629266af54) for draft documentation.
This paves the way for easier CA deployment in common homelab systems like Unraid and TrueNAS.
To build a test image, go to the repo root and run `docker build -f docker/Dockerfile.step-ca .`

New Dockerfile with entrypoint script for easy CA init

---

authority/authority_test.go
authority/provisioner/collection.go

This PR adds an extra way to distinguish Azure and Azure OIDC tokens.
We used to distinguish these tokens using the `azp` claim, but this claim does not appear on new azure oidc tokens, at least on some configurations.
This change will attempt to load by the audience (client id) if the token contains an email, required for OIDC

Azure OIDC

---

CHANGELOG.md

U.S. date format generates confusion arount the world, please use ISO-8601 dates

CHANGELOG: use ISO-8601 dates

---

authority/provisioner/sign_ssh_options.go

Fixes #679
This should fix the above issue by converting the ssh principals to lower case for group comparison.
Please note I'm not sure what needs to be done with adding a test for this so any guidance would be appreciated. 
Thank you!

Converts group and subgroup to lowercase for comparison.

---

CHANGELOG.md
cas/apiv1/services.go
cas/softcas/softcas.go
cas/softcas/softcas_test.go
kms/cloudkms/cloudkms.go
kms/cloudkms/signer.go
kms/cloudkms/signer_test.go

This PR adds a new interface to CloudKMS Signers to define the signature algorithm.
CloudKMS keys signs data using a specific signature algorithm, in RSA keys, this can be PKCS#1 RSA or RSA-PSS, if the latter is used, x509.CreateCertificate will fail unless the template SignatureCertificate is properly set.
In contrast, AWS KMS RSA keys, are just RSA keys and can sign with PKCS#1 or RSA-PSS schemes, so right now the way to enforce one or the other is to use templates.

Allow to kms signers to define the SignatureAlgorithm

---

authority/authority.go
authority/options.go
ca/ca.go
cmd/step-ca/main.go
commands/app.go

This PR adds the flags `--ssh-host-password-file` and `--ssh-user-password-file`, if any of them are not set will default to the one passed in --password-file or the one in the ca.json
Fixes #693

Add support for setting individual password for ssh and tls keys

---

pki/helm.go
pki/pki.go

This PR changes the default DB for helm charts to badgerv2, this is currently the default in `step ca init`.
We also use port 443 for the default `--ca-url`, as we usually access it through a k8s service. This option can be overridden using the `--with-ca-url` flag in the cli.

Use badgerv2 the default DB in helm

---

CHANGELOG.md
authority/provisioner/oidc.go
authority/provisioner/oidc_test.go

This PR makes sure that admins are always checked on emails and groups. In the previous implementation, the groups were only checked on the SSH flow to decide the template to use.

Check for admins in both emails and groups.

---

CHANGELOG.md
authority/authority.go
authority/ssh_test.go

This PR allows configuring `step-ca` as an SSH Host or SSH User CA, just configuring one of them.
In previous versions, if the host or user CA is not configured, the start of step-ca was crashing with a nil pointer dereference. This allows configuring a user-only or host-only ssh ca.
https://github.com/smallstep/certificates/blob/28bd2ef6c16b31df7f6d289c914a2b06b85329c2/authority/authority.go#L412-L418

SSH host or SSH user only CA

---

authority/provisioner/sign_options.go
authority/provisioner/sign_ssh_options.go
authority/tls_test.go

This PR is the first part of a project to send better errors to the cli users. We will refactor the errs package in other PRs.
@dopey what do you think about the distinction between 400 and 401, are they ok, should all they be 400?

Report duration errors directly to the cli.

---

cmd/step-pkcs11-init/main.go

This PR 
- Slightly simplifies the command line flags to make them
- Positive statements which are easier to reason about
- Remove duplicate flag `RootOnly` which was unclear
- Adds a `GenerateRoot` flag to support not generating a root -> create CSR
- Implements CSR signing

Support CSR Requests from PKCS11

---

api/api.go
api/api_test.go
api/rekey.go
api/renew.go
api/revoke.go
api/revoke_test.go
api/sign.go
api/ssh.go
api/sshRekey.go
api/sshRenew.go
api/sshRevoke.go
api/utils.go
authority/provisioner/jwk.go
authority/provisioner/sign_options.go
authority/provisioner/sign_ssh_options.go
authority/provisioner/sshpop.go
authority/provisioner/sshpop_test.go
authority/provisioner/x5c.go
authority/ssh.go
authority/ssh_test.go
authority/tls.go
authority/tls_test.go
ca/ca_test.go
ca/client.go
ca/client_test.go
errs/error.go

This PR is a first pass on sending better errors to the cli. This PR focuses only on 400 - bad request errors. With this change errs.BadRequest() and errs.BadRequestErr() always require a string to pass to the user.
Following PRs will change other HTTP statuses.

Bad request errors

---

ca/bootstrap.go
ca/bootstrap_test.go
ca/tls_options.go

When step-ca runs with mTLS required on some endpoints, the SDK used in autocert will fail to start because the identity certificate is missing. This certificate is only required to retrieve all roots, in most cases, there's only one, and the SDK has access to it.
I've added you @hslatman and @dopey, but I only need one review.

Avoid doing unauthenticated requests on the SDK

---

kms/pkcs11/pkcs11.go
kms/pkcs11/pkcs11_test.go

This PR implements the `kms.Decrypter` interface with PKCS#11, this interface allows the use of SCEP with PKCS#11 modules.

Implement the kms.Decrypter with PKCS#11

---

pki/pki.go

The systemd unit has a stanza that requires the db folder to exist, or else it will not start the unit.
But `step ca init` doesn't create the db folder.
This PR makes it possible to run `step ca init` and then `systemctl start step-ca` without needing to manually mkdir the db folder first.

Create the db directory on step ca init

---

authority/authority.go
authority/authority_test.go
authority/provisioner/scep.go
authority/provisioners.go
ca/ca.go
cas/cloudcas/cloudcas_test.go
go.mod
go.sum
scep/api/api.go
scep/authority.go
scep/common.go
scep/provisioner.go

This PR adds the intermediate CA certificate to ClientCAs for chain building and sends root certificates to clients when configured in the SCEP provisioner.
It also includes an additional knob to control the encryption algorithm for clients that don't support the default (DES-CBC). 
The SCEP provisioner has now been successfully tested with micromdm/scep, certnanny/sscep and the macOS SCEP client. The macOS SCEP client has also been tested with HTTPS requests instead of just HTTP successfully.
Fixes #746

Fix macOS SCEP client issues

---

ca/provisioner.go

Wrap other errors in JWK decryption process with more helpful messaging.  This should help users troubleshoot misconfiguration more easily.
Fixes #816

Add descriptive provisioner JWK decryption error messages

---

acme/api/linker.go
acme/api/linker_test.go
authority/config/config.go
authority/config/config_test.go
authority/tls.go
ca/provisioner_test.go

This PR ensures that IPv6 addresses the CA is configured for will contain square brackets when used as a hostname. This is at least the case for token audiences.
With these changes and the ones from the CLI in https://github.com/smallstep/cli/pull/610 the CA will have a cert for an IP SAN (instead of DNS) for serving its API, will respond to requests to its IPv6 address (i.e. `https://[::1]:8443`) and allows operations that are authorized by a JWT with that same hostname in it.

Normalize IPv6 hostname addresses

---

authority/provisioner/nebula.go
authority/provisioner/x5c.go

This PR makes the X5C leaf certificate available in the templates.
X509 and SSH templates of the X5C provisioner will have now access to the leaf certificate used to sign the token using the template variable `.AuthorizationCrt`.
Fixes #433

Make the X5C leaf certificate available to the templates.

---

.gitignore

This PR includes `.envrc` to `.gitignore` as a convenience to engineers who work on `certificates` while at the same time use a tool like [`direnv`](https://direnv.net/).

git: ignore .envrc files

---

CHANGELOG.md
authority/provisioner/scep.go
scep/api/api.go

To support SCEP clients that expect a specific path segment in a SCEP URL, we now made `step-ca` respond to any request made to an URL path that's prefixed by `http://<host>:<port>/scep/scepca`. The same SCEP provisioner will serve the request, no matter what path segments are provided behind `/scepca`. So e.g. `/scepca` and `/scepca/pkiclient.exe` will work the same. 
This PR closes https://github.com/smallstep/certificates/issues/843.

Add configuration for custom path segment on SCEP provisioners

---

api/errors.go
api/log/log.go
api/log/log_test.go
api/utils.go
api/utils_test.go
scep/api/api.go

This PR moves `api.LogError` in its own package (`api/log`) for now. It'll be going away soon enough, but for now it's being moved in its own package.

api/log: initial implementation of the package

---

.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
authority/provisioner/x5c.go
authority/provisioner/x5c_test.go
ca/ca.go
ca/identity/client_test.go
ca/identity/identity_test.go
ca/tls.go
ca/tls_options_test.go

This PR changes the supported versions of Go to 1.17 and 1.18, using Go 1.18 for releases.

Change go version to 1.17 and 1.18

---

authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/utils_test.go

I  know that its expected that users utilise either the ACME provisioner or I guess the K8sSA provisioner on Kubernetes. However, I think it would still be nice if it were possible to use step cli in container on Kubernetes, specifically on Azure Kubernetes Service (AKS).                                                                 
At the moment it's not possible because the value in the `xms_mirid` claim is expected to match the regular expression:                                                 
```go                                                                                                                                                                   
var azureXMSMirIDRegExp = regexp.MustCompile(`(?i)^/subscriptions/([^/]+)/resourceGroups/([^/]+)/providers/Microsoft.Compute …
```

WIP: Support Azure tokens generated by managed identities

---

scep/api/api.go
scep/authority.go
scep/scep.go

This PR continues the work of #867 as follows:
- removes `scep.Interface` and refactors the code to use `*scep.Authority` in its place.
- removes scep's dependency to `pkg/errors`

scep: remove Interface and the dependency to pkg/errors

---

authority/options.go
cas/apiv1/options.go
cas/softcas/softcas.go
cas/softcas/softcas_test.go

This change adds a new authority option that allows passing a callback that returns the certificate chain and signer used to sign X.509 certificates.
This option will be used by Caddy, they renew the intermediate certificate weekly and there's no other way to replace it without re-creating the embedded CA.
Fixes #874

Add authority.WithX509SignerFunc

---

ca/adminClient.go

This PR makes sure the admin token audience is passed without a query string (or any fragment). The audience is checked against a string like `https://host/path`, so URLs like `https://host/path?limit=100` were failing on master if we replace the version of the certificates in the cli with master.

Drop any query string from the admin tokens

---

docker/Dockerfile.step-ca
docker/Dockerfile.step-ca.hsm
docker/entrypoint.sh

- Update existing Dockerfile to include GCP and AWS KMS (does not require CGO)
- Add new Dockerfile to build Step CA with support for PKCS#11 and Yubikey (with CGO and PCSC), not yet included in the build process 
- Start pcscd in entrypoint if installed

Dockerfile for HSM-enabled Step CA

---

pki/helm.go

Allow KMS type to be inserted into the helm chart values if specified on the command line.
Currently if you run something along the lines of:
`step ca init --helm --kms azurekms > values.yaml`
The command will succeed and will even add the reference to the - in this case, Azure Key Vault - for `key` but when you deploy the chart it will fail with an error about the local file azurekms....not existing. This is because when the template values file created it is omitting
```YAML
kms:
type: <kms type goes here>
```
It took me a minute to realise that this is what was happening.
Make it easier for users to use step ca in Kubernetes when also using a KMS. Currently users may be confused why it doesn't work and requires editing the values YAML file after it has been generated to make it work …

Allow KMS type to be specified in the helm chart values YAML 

---

go.mod
go.sum

Use https://github.com/smallstep/pkcs7 fork with (selected) patches applied.
The patches are applied to the [patches](https://github.com/smallstep/pkcs7/tree/patches) branch. As of now, only the commits from https://github.com/mozilla-services/pkcs7/pull/64 have been applied.
Problems with large SCEP requests failing to be processed correctly. 
More generally, this allows us to apply more patches if necessary, since maintenance on github.com/mozilla-services/pkcs7 seems to have stalled (for now).

Use github.com/smallstep/pkcs7 fork with (selected) patches applied

---

authority/authorize_test.go
authority/linkedca.go
authority/provisioner/aws.go
authority/provisioner/aws_test.go
authority/provisioner/azure.go
authority/provisioner/gcp.go
authority/provisioner/jwk.go
authority/provisioner/k8sSA.go
authority/provisioner/k8sSA_test.go
authority/provisioner/nebula.go
authority/provisioner/noop.go
authority/provisioner/oidc.go
authority/provisioner/ssh_test.go
authority/provisioner/x5c.go
authority/provisioner/x5c_test.go
authority/ssh.go
authority/tls.go
ca/bootstrap_test.go
db/db.go
db/simple.go

This PR allows reporting the provisioner used to sign an SSH certificate to linkedca, on a previous PR, the reporting of provisioners for X509 certificates was implemented.
As a pending task, we can add a new table in the nosql to store this.

Report SSH provisioner

---

ca/tls.go

Set nil dial context for js/wasm runtime
API requests performed by a `js/wasm` program currently fail with a "Protocol not supported" error. With this change HTTP(S) requests performed by a `js/wasm` build will be handled by the browser's Fetch API, instead.
For `js/wasm` targets.

Set nil dial context for js/wasm runtime

---

acme/api/order.go
acme/api/order_test.go

This commit strips the padding from a base64-url encoded CSR
submitted by a client that doesn't use raw base64-url encoding.
Fixes #939

Strip base64-url padding from ACME CSR

---

cas/cloudcas/certificate_test.go

The next Go release call panic on elliptic.Marshal [1][2], which
affect the test case fail_ec_marshal on createPublicKey.
This changes fix this by initializing the P and B in test case
PublicKey CurveParams to prevent panic.
[1] https://github.com/golang/go/issues/50975
[2] https://github.com/golang/go/commit/a218b3520a500254cc82b996b79ad6f5a355021c

cas/cloudcas: update test on createPublicKey for the next Go release

---

acme/api/eab.go
acme/api/middleware.go
authority/provisioner/aws.go
ca/bootstrap.go
ca/ca.go
cas/cloudcas/cloudcas.go
cas/cloudcas/mock_client_test.go
cas/cloudcas/mock_operation_server_test.go
commands/onboard.go
kms/azurekms/internal/mock/key_vault_client.go
kms/cloudkms/cloudkms.go
kms/pkcs11/opensc_test.go
kms/pkcs11/softhsm2_test.go
kms/pkcs11/yubihsm2_test.go
logging/clf.go

There are some changes that manually edited, for example using '-' as
default list and grouping imports.

all: reformat all go files with the next gofmt (Go 1.19)

---

kms/uri/uri_119_test.go

The next Go release add field OmitHost to url.URL [1] which cause the
TestParse fail.
Since the CI supports two consecutive Go versions at the same times, we
copy the uri_test.go to uri_119_test.go for testing with Go 1.19.
While at it, print the got and want object using the same format
(%#v) and type (*URL) for consistency.
[1] https://go-review.googlesource.com/c/go/+/391294

kms/uri: fix test on Parse for the next Go release

---

kms/uri/uri_other_test.go
kms/uri/uri_test.go

This is a refinement over https://github.com/smallstep/certificates/pull/956 that made the `kms/uri` test compatible with Go 1.19.
CC: @shuLhan

Split Go 1.19 problematic with build tags

---

CHANGELOG.md
cas/softcas/softcas.go
cas/softcas/softcas_test.go

An RSA key can sign another certificate using the RSA PKCS#1 and the RSA-PSS scheme, this PR will keep the signature algorithm used in the issuer in the signed certificates instead of using PKCS#1 by default.
Fixes #952

Sign certificates with the issuer signature algorithm

---

go.mod
go.sum
monitoring/monitoring.go

Let `step-ca` build on OpenBSD.
With these deps bumped, tests all pass on OpenBSD amd64.
OpenBSD support was added to the following deps:
- github.com/go-piv/piv-go in https://github.com/go-piv/piv-go/pull/101
- github.com/newrelic/go-agent in https://github.com/newrelic/go-agent/pull/455
- github.com/miekg/pkcs11 in https://github.com/miekg/pkcs11/pull/140

Update deps to bring in support for OpenBSD

---

authority/config/config.go
authority/ssh.go

Add attribute to disable SSH Hosts list API

---

ca/ca.go
go.mod
go.sum

This PR upgrades chi and adds the GetHead middleware to route missing HEAD requests to the GET handler.
Fixes #992

Add a middleware to automatically route HEAD requests to GET

---

.golangci.yml
CHANGELOG.md
cas/softcas/softcas.go
cas/softcas/softcas_test.go

This PR fixes the signature algorithm when the PKI has an EC root and an RSA intermediate. 
Instead of using the intermediate signature scheme, it uses the default one. We are still using the intermediate signature schema for RSA+RSA PKIs.
Fixes #1033

Fixes signature algorithm

---

cmd/step-awskms-init/main.go
cmd/step-cloudkms-init/main.go
cmd/step-pkcs11-init/main.go
cmd/step-yubikey-init/main.go

This PR adds deprecation notices to the following binaries:
* `step-awskms-init`
* `step-cloudkms-init`
* `step-pkcs11-init`
* `step-yubikey-init`
Fixes #1044

Add deprecation notices to step-x-init binaries

---

authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/ssh_test.go

Remove requirement of needing `Email` claim on OIDC tokens for SSH Signing. This pull removes the requirement for an `Email` claim in the token, and if it is missing will pass a minimal data set to the template renderer with no Principals defined, and using the `Subject` claim as KeyID.
This way a user may setup an OIDC provisioner that accepts JWTs from the CI/CD pipeline, and use templates to strictly control what principals are added to the issued Certificates (in the case of SSH certificates)
JWTs issued by several CI/CD pipelines don't include `Email` claims [Gitlab](https://docs.gitlab.com/ee/ci/cloud_services/#how-it-works), Github, etc
Removing the requirement for an `Email` claim allows a token to be resolved and SSH certs to be issued when using these JWTs.
* [Gitlab JWT …

Allow missing Email claim in OIDC tokens

---

authority/authorize.go

This PR fixes a nil pointer caused because an error was null.

Fix nil pointer exception

---

acme/order.go
authority/provisioner/sign_options.go
authority/tls.go
cas/cloudcas/cloudcas_test.go

This PR adds a new sign option to pass attestation information to the `authority.Sign` method. This permits sending this information to authorizing webhooks.
This PR also solves a test skipped in CI when it runs on local environments with gcloud configured.

Acme attestation information

---

acme/db/nosql/authz_test.go
acme/db/nosql/challenge_test.go
acme/db/nosql/order_test.go
acme/errors.go

For ACME errors, return the internal error string instead of the ACME one on the "Error() string" function. This way, the logs will have more information about the cause of an error.
Fixes #1057

Return the internal error instead of the ACME error

---

authority/provisioner/controller.go
authority/provisioner/controller_test.go

Provisioner webhooks
Webhooks configured for x509 only are being called for ssh certs and vice versa.
💔Thank you!

Fix webhook controller ignoring cert type

---

api/renew.go
api/sshRekey.go
api/sshRenew.go

- after upgrade to golangci-lint 1.50.0

No longer need to ignore context warnings when context in request

---

acme/challenge_test.go

There are YubiKeys v5.2.4 where the attestation intermediate (f9) does not have a basic constraint extension, so that certificate is not marked as a CA. 
The test and CA in this commit imitate that use case. Currently, the test case returns an error as we don't support it. But if we change the verification to support this use case, the test should change accordingly.
See https://github.com/Yubico/yubikey-manager/issues/522

Add test simulating YubiKey v5.2.4

---

.version.sh

This PR replaces bash with sh in the version script. This script is only used if certificates is built from a code that doesn't contain a git repository, for example, from the source file [asset](https://github.com/smallstep/certificates/releases/download/v0.22.1/step-ca_0.22.1.tar.gz) in GiHub releases
Fixes #1115

Use sh instead of bash in .version.sh script

---

go.mod
go.sum

This PR upgrades the pkcs7 package to the latest version in smallstep/pkcs7@patches. This includes now support for generic Decrypter methods so that KMS can be used instead of a key in disk with SCEP.
Related PR:

Upgrade pkcs7 to the latest patches branch

---

acme/challenge.go
acme/challenge_test.go
commands/app.go

This change adds the flags `--acme-http-port`, `--acme-tls-port`, that combined with `--insecure` can be used to set custom ports for ACME `http-01` and `tls-alpn-01` challenges. These flags should only be used for testing purposes.
Fixes #1015

Add support for custom acme ports

---

api/api.go
api/api_test.go
api/renew.go
authority/authorize.go
authority/authorize_test.go
authority/provisioners.go
authority/provisioners_test.go
authority/tls.go
authority/tls_test.go
cas/apiv1/requests.go
cas/apiv1/services.go
cas/apiv1/services_test.go
cas/stepcas/stepcas.go
cas/stepcas/stepcas_test.go
db/db.go
db/db_test.go

It supports renewing X.509 certificates when an RA is configured with stepcas. This will only work when the renewal uses a token, and it won't work with mTLS.
The audience cannot be properly verified when an RA is used, to avoid this we will get from the database if an RA was used to issue the initial certificate and we will accept the renew token.
Fixes #1021 for stepcas.
The support for cloudcas was already implemented, and the renew token cannot be used for vaultcas because the CSR is [required](https://developer.hashicorp.com/vault/api-docs/secret/pki#sign-certificate) and it's not available in a renew flow.

Add support for renew when using stepcas

---

authority/linkedca.go
go.mod
go.sum

This PR adds support for linked RA renewals. Related to #1021 and #1156.
RA renewals must use renewal tokens instead of mTLS:
```
step ca renew localhost.crt localhost.key --mtls=false
```

Add support for linked RA renewals

---

authority/authority.go
authority/authority_test.go

This PR changes the parsing of root and federated roots to support a bundle of certificates.
This reduces the number of files required to support multiple roots or federated roots. And it makes the configuration a little simpler, especially when using helm charts that don't currently support adding extra files.

Allow root and federated root bundles

---

ca/tls.go

The environment variable STEP_CLIENT_ADDR can be used to set the local address to use when dialing an address. This can be useful when `step` is behind a CIDR-based ACL.
Fixes smallstep/cli#730

Set dialer local address with STEP_CLIENT_ADDR

---

acme/api/handler.go
acme/api/handler_test.go

Addresses https://github.com/smallstep/certificates/issues/1171. 
In internal discussions the fact that some information is lost from the response when `charset` is removed came up. Ideally, we think the Erlang client in case should be updated to be more lenient in what it accepts, in line with the _robustness principle_. The change is small, so maybe it gets done. On the other hand, the change here is small too, so we may merge it. 
Awaiting approval and some compatibility testing.

Remove `charset=utf-8` from ACME certificate responses

---

ca/adminClient.go
ca/client.go

If an http client `Do` method fails, it always returns an `*url.URL` error, this change generalizes all those errors in one common method instead of returning a fake HTTP error.
Fixes smallstep/cli#738

Return an appropriate error when requests fail

---

api/log/log.go
api/log/log_test.go

When running with `STEPDEBUG=1`, a response with a `StackTracedError` would result in a nil pointer error. This commit fixes the check and adds a test case.
This issue was hit by @taher-mosbah in https://github.com/smallstep/certificates/issues/953#issuecomment-1318333519.

Fix `StackTracedError` logging

---

authority/config/config.go
authority/tls.go

This PR adds a configuration option for adding a custom IDP to the CRLs that Step generates.
This essentially allows the CRL to be hosted off of Step CA. In my case (and in previous environments I have worked with), CRLs and OCSP are hosted in a highly available fashion, so this PR would allow the IDP on the CRL to be set to this location.
Getting the CRL off of step and to that HA location is on the administrator though 😃 .
I created this PR after testing CRL generation, and then attempting to host them off of the Step-CA server. Originally, I set `crlDistributionPoints` on a Step template to reflect my HA location, and manually hosted the CRL there, but I noticed that Windows was having a hard time validating the CRL because the IDP on the CRL did not match said location.
Some of this …

Adding crl idp config

---

docker/entrypoint.sh

A `step-ca` instance created in a container can now be initialized with Remote Management by setting `DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT`. An ACME provisioner with default settings can be created at initialization by setting `DOCKER_STEPCA_INIT_ACME`.

Add env vars for enabling Remote Management and ACME provisioner

---

authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
templates/values.go

This PR will ignore principals validation when an OIDC provisioner is used. When the principals in the server do not match the principals given, the validation was failing, even if templates or webhooks set the proper principals. With this change, OIDC will not validate the principals and will just set the default ones (name, name@example.org) plus the ones in the templates.
This PR also includes a change in the templates to allow setting the provisioner to the $(step path)/ssh/config template
Related to smallstep/cli#807, #900 cc @Janhouse

Ignore principals validations with OIDC

---

docker/Dockerfile.step-ca
docker/Dockerfile.step-ca.hsm
docker/entrypoint.sh

When using our Docker image, it usually makes sense to enable Remote Provisioner Management.
In the current version, we only generate one password file for the CA when we initialize a PKI via `docker run`, and we pass it to `step ca init` for use with both the CA keys and the admin provisioner.
This change adds a bit more security by also generating a provisioner password file by default when the CA is being initialized. The CA admin provisioner username and password are printed after `step ca init` runs, and the provisioner password file is deleted.
I'm also updating our Docker README setup instructions to enable Remote Management by default.
cc @hslatman

Docker: Generate and use independent provisioner and private key passwords

---

.github/workflows/release.yml
docker/Dockerfile
docker/Dockerfile.hsm

This PR adds a new docker image, `smallstep/step-ca-hsm`, where `step-ca` is compiled with CGO. This image can be used with a PKCS#11 HSM. This image also includes a CGO compiled `step-kms-plugin`.
The old image `smallstep/step-ca` also includes `step-kms-plugin` but without CGO, but it still can be used to create a PKI on cloud-based KMSs.
Requires:

Add step-kms-plugin to docker images and build a CGO based one

---

authority/config/config.go
commands/app.go

Helpful message on CA startup when config can't be opened

---

docker/entrypoint.sh

This allows configuring "--address" instead of using hard-coded :9000

Add DOCKER_STEPCA_INIT_ADDRESS

---

acme/authorization.go
acme/challenge.go
acme/challenge_test.go
acme/db/nosql/authz.go
acme/db/nosql/authz_test.go
acme/order.go
acme/order_test.go
cmd/step-ca/main.go
go.mod
go.sum

This commit ensures that the attestation certificate key matches the key used on the CSR on an ACME device attestation flow.

Verify CSR key fingerprint with attestation certificate key

---

scripts/install-step-ra.sh

"install: cannot stat 'step-ca_0.23.2/bin/step-ca': No such file or directory" Upon checking the is no bin directory after step-ca_linux_0.23.2_amd64.tar.gz is extracted so by simply changing from step-ca_${CA_VERSION:1}/bin/step-ca to step-ca_${CA_VERSION:1}/step-ca the installation succeed.

There is an error during RA installation which shows.

---

authority/tls.go

Trying to get CRL to work on my environment I've been reading up on [RFC5280](https://www.rfc-editor.org/rfc/rfc5280#section-5.2.5) ... and the IDP to be marked as `Critical`. I hope I'm correct and that my understanding on how to mark the IDP is critical. Looking at e.g. `https://github.com/smallstep/crypto/blob/3470b1ec576bc912e80ac6c65a495934d4fcc585/x509util/extensions_test.go#L48` makes me think so.
Using `step crl inspect URI/1.0/crl --insecure` I get:
```text
Certificate Revocation List (CRL):
Data:
Valid: false
Version: 2 (0x1)
Signature algorithm: ECDSA-SHA256
Issuer: .... Intermediate CA
Last Update: 2023-02-24 19:35:59 +0000 UTC
Next Update: 2023-02-25 19:35:59 +0000 UTC
CRL Extensions:
X509v3 Authority Key Identifier: …
```

Mark the IDP critical in the generated CRL data.

---

pki/pki.go

This commit removes the database from the configuration if the ca was initialized with the "--no-db" flag.
Fixes #1292

Disable database if WithNoDB() option is passed

---

CHANGELOG.md
go.mod
go.sum

With https://github.com/smallstep/pkcs7/pull/4 the PKCS7 package now supports RSA-OAEP decryption. This type of encryption is used with SCEP.

Fix RSA-OAEP decryption for SCEP

---

authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/utils_test.go

Support issuing identity token for all Azure cloud environments (Public, China, German and US Gov)
When step-cli (which will need a go.mod update) issues an identity token from an Azure virtual machine, if the virtual machine runs in an Azure cloud different from "Public", the token issuance fails due to using an incorrect identity URL. This PR addresses this issue by doing a lookup into the IMDS API to fetch the current instance/virtual machine environment and sub-sequently set the resource query parameter to the correct resource URL.
Provides greater support for more environment.
No as there is no external configuration change needed for this feature
For Azure provisioner only
List of all environments:
https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tab …

Add identity token issuance for all Azure cloud environments

---

commands/app.go

This PR fixes a typo in the usage of --pidfile

Fix typo in flag usage

---

go.mod
go.sum

This commit upgrades go.step.sm/crypto to v0.29.1. This version adds the following template functions:
- asn1Enc
- asn1Marshal
- asn1Seq
- asn1Set

Upgrade go.step.sm/crypto with new ASN.1 functions

---

.github/workflows/release.yml
docker/Dockerfile
docker/Dockerfile.hsm

To merge & release this PR:
Related:
- https://github.com/smallstep/step-kms-plugin/pull/47
- https://github.com/smallstep/cli/pull/861
fixes #1286

Update Dockerfile.hsm to use debian:bullseye base image

---

go.mod
go.sum

This PR upgrades package sdk/keyvault/azkeys to v0.10.0, the same version used in crypto.
This package wasn't upgraded in certificates and for some reason it causes an authentication error if a client-id/client-secret is used for authenticating with KeyVault. Managed identities or CLI authentication works as expected.
Fixes #1358

Upgrades azure-sdk-for-go to the version used in crypto

---

api/crl.go

This PR refactors the way PEM-encoded CRLs are served so that they're directly rendered into the underlying `http.ResponseWriter`.

Do not render CRLs in memory

---

ca/ca.go

In addition to being served over HTTPS, the `/crl` and `/1.0/crl` endpoints are now also served on the HTTP server if the `insecureAddress` has been configured. This should help users that currently have to use workarounds to get this to work in certain scenarios.
Related issues:
- https://github.com/smallstep/certificates/issues/1284 
- https://github.com/smallstep/certificates/issues/206#issuecomment-1530219201

Add `/crl` and `/1.0/crl` to the insecure HTTP handler

---

api/render/render.go
api/render/render_test.go

This PR optimizes `render.JSON` so that it doesn't use an intermediate buffer.

optimized render.JSON

---

cas/vaultcas/vaultcas.go

According to docs at https://developer.hashicorp.com/vault/api-docs/secret/pki#ttl the ttl can be sent as a time.Duration string.
Fixes #1375

Use vaultcas ttl as a duration string

---

api/api.go
api/api_test.go
api/sign.go
api/ssh.go
api/sshRekey.go
api/sshRenew.go

This PR closes #1257 
A log looks like this:
```console
INFO[0015] 
certificate="ecdsa-sha2-nistp256-cert-v01@openssh.com AAAAKGVjZHNhLXNoYTItbmlzdHAyNTYtY2Vyd.......EpFTvWiOGbbCSb7WLd68HQU=" 
certificate-type=user 
duration=1.622708ms 
duration-ns=1622708 
fields.time="2023-05-04T15:30:42+02:00" 
method=POST 
name=ca 
ott=eyJhbGciOiJFUzI1NiIsImtpZCI6IlJ.....O9tewjVFtNfQ 
path=/ssh/sign 
principals="[newpub new.pub]" 
protocol=HTTP/2.0 
public-key="256 SHA256:vgL0C7eN7RtGK0b2r7Ptpoig8fokQqUwLcONsZ/m/ao no comment (ECDSA-CERT)" 
referer= 
remote-address=127.0.0.1 
request-id=ch9r70lroa2scelp5gg0 
serial=8612232055386440238 
size=783 
status=201 
user-agent="Smallstep CLI/0000000-dev (darwin/arm64)" 
user-id= 
valid-from="2023-05-04T15:29:42+02:00" 
valid-to="2023-05-05T07:30:42+02:00"
``` …

Log SSH certificates

---

docker/entrypoint.sh

Add the management of the DOCKER_STEPCA_INIT_PASSWORD_FILE variable.  over DOCKER_STEPCA_INIT_PASSWORD. If both are used only DOCKER_STEPCA_INIT_PASSWORD_FILE will be used.
Add DOCKER_STEPCA_INIT_PASSWORD_FILE variable for Docker secrets
Allow the possibility to use Docker Secrets for step-ca init password
This allow to use a predefined password with having to use enviromental variables
I can do it, but I don't know where in this repo
Docker
💔Thank you!

Add DOCKER_STEPCA_INIT_PASSWORD_FILE variable for Docker secrets

---

cas/vaultcas/vaultcas.go

Add optional use of namespaces to VaultCAS
Currently, using step-ca as a Registration Authority downstream from Vault (https://smallstep.com/docs/step-ca/registration-authority-ra-mode/#5-configure-the-ra-server) does not allow for using the namespaces feature of Vault Enterprise. Specifically, proper approle authentication with Vault can't occur because there is no way to include the `X-Vault-Namespace` header. Vault's API client that step-ca uses includes a function to set the namespace: https://github.com/hashicorp/vault/blob/main/api/client.go#L949-L955. The optional use of this function is all this PR adds.
(Side note: A workaround for tne absence of the header this would be to include the namespace in the path; however, this doesn't work because when the `authMountPath` field is …

Add namespace field to VaultCAS JSON config

---

acme/challenge_tpmsimulator_test.go

Issue most probably introduced through https://github.com/smallstep/certificates/pull/1459.

Fix TPM simulator initialization for tests

---

scripts/README.md
scripts/badger-migration/main.go

This PR adds a tool that allows migrating data from BadgerDB to MySQL or PostgreSQL databases.

Add tool to migrate data from badger to mysql or postgresql

---

ca/bootstrap_test.go

The TestBootstrapClientServerRotation often fails because the reload returns once the Server loop gets the new listener, but the server hasn't really started yet. This commit makes the test pass, adding a small sleep after the reload.
A proper fix might require a wrapper over the `net.Listener` with an ACK callback on a `sync.Once` on a custom `Accept`.

Wait for Accept in TestBootstrapClientServerRotation

---

authority/provisioner/controller.go
authority/provisioner/controller_test.go
authority/provisioner/webhook.go
authority/provisioner/webhook_test.go
authority/provisioner/x5c.go
authority/provisioner/x5c_test.go
webhook/options.go
webhook/options_test.go
webhook/types.go

This commit adds a new property that will be sent to authorizing and enriching webhooks when signing certificates using the X5C provisioner.
cc: @joshdrake

Send X5C leaf certificate to webhooks

---

scripts/badger-migration/main.go

This PR adds the admin tables to the migration script, it also removes the default badger version.

Add to the migration script the admin tables

---

authority/provisioner/aws.go
authority/provisioner/azure.go
authority/provisioner/gcp.go
authority/provisioner/x5c.go
authority/provisioner/x5c_test.go
webhook/options.go
webhook/types.go

Provisioner Webhooks
Webhook responders may want to make authorization decisions or enrich certificate requests based on how the signing request was initially authorized. The entire authorization token cannot be sent due to potential replay attacks or proliferation of sensitive material, but the present principals from that token can often satisfy these requirements.
https://github.com/smallstep/docs/compare/josh/enrich-authorization-principal?expand=1
Cloud (AWS, GCP, Azure) provisioners, X5C provisioners.
https://github.com/smallstep/docs/compare/josh/enrich-authorization-principal?expand=1
💔Thank you!

Include authorization principal in provisioner webhooks.

---

authority/provisioner/controller.go
authority/provisioner/controller_test.go
authority/provisioner/provisioner_test.go

This commit removes the regular expression check on OIDC usernames. Although using any character in a username is not recommended, creating and using them is possible. The tool `useradd` has the flag `--badname`, and `adduser` has `--allow-badname` and `--allow-all-names` to create new users with any character.
Moreover, it is possible to create any username with the rest of provisioners.
Fixes #1436

Remove OIDC user regexp check

---

authority/provisioner/options.go
authority/provisioner/ssh_options.go
cmd/step-ca/main.go
go.mod
go.sum

This commit upgrades cli-utils and crypto packages that remove the automatic initialization of the STEPPATH.
Requires:
- https://github.com/smallstep/cli-utils/pull/73
- https://github.com/smallstep/crypto/pull/298

Remove automatic initialization of the STEPPATH

---

authority/config/config.go

This commit fixes a problem when the ca.json is truncated if the encoding of the configuration fails. This can happen by adding a new provisioner with bad template data.
Related to smallstep/cli#994

Write configuration only if encoding succeeds

---

acme/challenge_test.go
ca/tls_test.go

This commit fixes a test checking an error string from an external dependency. It also fixes random errors on CI because the server BaseContext MUST be set before the start of a server, and that was not the case on some unit tests.

Fix error string in tests

---

authority/provisioners.go

Fixes [github.com/smallstep/cli/pulls](https://github.com/smallstep/cli/issues/1009).

provisionerOptionsToLinkedCA missing template and templateData

---

db/db.go

Remove db datasource from error msg to prevent leaking of secrets

---

acme/api/account.go
acme/api/account_test.go
acme/api/handler.go
acme/api/handler_test.go
acme/api/order.go
acme/api/order_test.go
acme/api/revoke_test.go
acme/linker.go
api/api.go
api/api_test.go
authority/admin/api/acme_test.go
authority/admin/api/admin.go
authority/admin/api/admin_test.go
authority/admin/api/middleware.go
authority/admin/api/middleware_test.go
authority/admin/api/provisioner.go
authority/admin/api/provisioner_test.go
authority/admin/api/webhook.go
authority/admin/api/webhook_test.go
ca/ca.go
go.mod
go.sum
scep/api/api.go

Upgrade chi to the v5 module path
To avoid deprecation warning about v4 and earlier on the old module path and to continue to receive updates.
See https://github.com/go-chi/chi/blob/v4.1.3/go.mod#L1-L4

chore(deps): upgrade github.com/go-chi/chi to v5

---

authority/provisioner/webhook.go
authority/provisioner/webhook_test.go

This PR fixes the way webhooks signatures are created. Before this change, the signature of an empty body was prepended by the body itself.

Fix webhooks signature

---

logging/logger.go

This PR adds support for NO_COLOR environment variable, if this is set, colors will be disabled in the logrus text formatter.
This PR also adds support for the environment variables supported by logrus, CLICOLOR and CLICOLOR_FORCE
Related to #1549

Allow to disable color in the text formatter

---

scep/api/api.go
scep/api/api_test.go

This PR:
*  Improves the logic for handling SCEP requests
* Adds a workaround for macOS SCEP clients sending weird GET PKIOperation messages
Apparently the macOS SCEP client sends a SCEP message in the query
that's not fully escaped. Only the base64 padding is escaped, the
'+' and '/' characters aren't.
This is a bit of a special case, because the macOS SCEP client
will default to using HTTP POST for the PKIOperation. But if the
CA is configured without the POSTPKIOperation capability, the
macOS SCEP client will use HTTP GET instead. This behavior might
be the same on iOS.

Improve SCEP request handling

---

api/ssh.go
authority/authorize.go
authority/provisioner/aws.go
authority/provisioner/aws_test.go
authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/gcp.go
authority/provisioner/gcp_test.go
authority/provisioner/jwk.go
authority/provisioner/jwk_test.go
authority/provisioner/method.go
authority/provisioner/nebula.go
authority/provisioner/sign_options.go
authority/provisioner/sign_options_test.go
authority/provisioner/x5c.go
authority/provisioner/x5c_test.go

- skip urisValidator for identity certificate signing. Implemented by building the validator with the context in a hacky way.

Allow for identity certificate signing (in sshSign) by skipping validators

---

authority/provisioner/jwk.go
authority/provisioner/jwk_test.go

This commit changes the common name validator in the JWK provisioner to accept either the token subject or any of the sans in the token.
This PR allows admin tokens on RA to work with the changes in https://github.com/smallstep/certificates/pull/1608

Change CommonName validator in JWK

---

docker/Dockerfile.hsm

This commit makes sure to use the same version for building step-ca with CGO and running it.
Fixes #1611
A new issue has been created to upgrade builds to bookworm https://github.com/smallstep/certificates/issues/1615

Use the same version for building and running

---

acme/api/middleware.go
acme/api/middleware_test.go

Apparently the Apple macOS (and iOS?) ACME client seems to omit leading null bytes from JWS signatures. The base64-url encoded bytes decode to a shorter byte slice than what the JOSE library expects (e.g. 63 bytes instead of 64 bytes for ES256), and then results in a `jose.ErrCryptoFailure`.
This commit retries verification of the JWS in case the first verification fails with `jose.ErrCryptoFailure`. The signatures are checked to be of the correct length, and if not, null bytes are prepended to the signature. Then verification is retried, which might fail again, but for other reasons. On success, the payload is returned.
Apple should fix this in their ACME client, but in the meantime this commit prevents some "bad request" error cases from happening.
Code from Apple …

Add (temporary) fix for missing null bytes in Apple JWS signatures

---

api/api.go
api/api_test.go
api/crl.go
api/crl_test.go
authority/tls.go
authority/tls_test.go

This implements the change from https://github.com/wireapp/smallstep-certificates/commit/659117c329da240d6799461917a33b2bd1290c82.
Besides that, it improves the test (coverage) for the CRL HTTP handler.

Add `Expires` header to CRL endpoint

---

authority/ssh.go
authority/tls.go
internal/metrix/meter.go

This PR refactors the webhook-related instrumentation so that it captures errors in cases where the request's body does not end up hitting the wire. It also registers the forgotten webhook-related instruments to the Prometheus endpoint.

fix: Also instrument webhooks that do not reach the wire

---

go.mod
go.sum

Fixes https://pkg.go.dev/vuln/GO-2024-2611.

Upgrade `google.golang.org/protobuf` to `v1.33.0`

---

ca/ca.go

Before this change, if one of the CA servers failed to start, this fact would only be logged when the CA was fully stopped. The CA wasn't triggered to stop if one of the servers failed, so it would just continue operating, until it got a signal to restart or stop. Users would thus not know that one of the servers failed to start, unless they knew what to look for in the logging, and deducing that the absence of the server listening log means their configuration may not be OK.
After the change, the CA will be stopped when an error occurs that is not the expected `http.ErrServerClosed`. Effectively this will make the CA either run all servers successfully, or it'll not run at all.
Examples:
```console
...
2024/03/05 11:05:51 X.509 Root Fingerprint: …
```

Handle CA server startup errors

---

cmd/step-ca/main.go

This PR enables `go.step.sm/crypto/kms/tpmkms`  in step-ca.

Enable tpmkms

---

scep/scep.go

See https://www.rfc-editor.org/rfc/rfc8894.html#section-6 and http://oid-info.com/get/1.3.6.1.5.5.7.24.1
When reporting an error message to the client as part of the SCEP protocol, the client will look for this OID to print the error text. Currently it would only print the the `failInfo` correctly (e.g. 2 for a bad request), but not the actual error message that we send.

Fix the `id-scep-failInfoText` OID

---

scep/api/api.go
scep/authority.go

To be on the safe side, block errors from signing operations from being returned to the client. We should revisit, and make it return a more informative error, but with high assurance that no sensitive information is added to the message.

Prevent exposing any internal details in SCEP failure message

---

acme/db.go
acme/db_test.go
go.mod
go.sum

This commit allows to use the standard error sql.ErrNoRows for not found errors.

Make IsErrNotFound more flexible

---

acme/account.go
acme/api/account.go
acme/db/nosql/account.go
acme/db/nosql/account_test.go

This commit adds a new field that allows to have a reference to a provisioner id in the acme account.

Add provisioner id to acme accounts

---

acme/api/middleware.go
authority/admin/api/middleware.go

This commit replaces the comparisons with acme.ErrNotFound and always uses acme.IsErrNotFound.

Use always acme.IsErrNotFound

---

authority/root.go
authority/root_test.go

This commit adds new methods to get the intermediate certificates.
cc: @hslatman

Add methods to get the intermediate certificates

---

authority/tls.go
authority/tls_test.go
cas/apiv1/services.go
cas/softcas/softcas.go
cas/softcas/softcas_test.go

This commit adds a method to the Authority type that returns the signer used to sign X509 certificates.

Add GetX509Signer method

---

.goreleaser.yml
go.mod
go.sum

This is just to fix a deprecation warning for goreleaser v2—the version which we are already running.
https://goreleaser.com/blog/goreleaser-v2/#upgrading

Update goreleaser YML version

---

acme/challenge.go
acme/challenge_test.go

Fixes #1902 
Besides checking for an empty attestation object, which can be the case when a client is not able to provide an attestation and which should fail issuance, there's now an additional check for the CBOR data to be well formed. Effectively that check will be performed twice, as it's done during unmarshaling too, but this way it's easier to surface invalid CBOR data errors to the user. The alternative is to catch specific errors from the `cbor` package.
Instead of returning an error to the client immediately, the error is stored with the challenge instead, as the challenge won't be solved using the same request body again.

Fix HTTP internal server error when bad attestation object is provided

---

acme/challenge.go

This commit fixes an issue with the HTTP-01 challenge URL not having the insecure port.

Fix HTTP01 challenge url when --acme-http-host is used

---

api/ssh.go
api/ssh_test.go

This commit allows the creation of the identity certificate with the host URI using any provisioner. Before, only the K8SSA provisioner could create an identity certificate with the URI.

Create identity uri on any provisioner

---

acme/challenge.go
acme/challenge_test.go
commands/app.go

This commit adds a flag to enable strict DNS resolution on ACME challenges.
Starting the server with `step-ca --acme-strict-fqdn` will not expand the DNS lookup to the `resolv.conf` search list. By default, it will.

Add a flag to enable strict DNS resolution

---

CHANGELOG.md

- A change was added in 0.27.0 that mandated use of strict FQDNs in ACME challenge verification. Upon further review, a flag was added to enable this behavior because it is not considered to be a necessary feature.

Add changelog for 0.27.2 & 0.27.1 | update changelog for 0.27.0

---

api/ssh.go
authority/provisioner/gcp.go
authority/provisioner/gcp_test.go
authority/provisioner/method.go
authority/provisioner/utils_test.go

Allowing **GCP** provisioner to issue SSH User Certificates - Option 2
Workloads running in GCP Compute Instances are run with an assigned Service Account. The Service Account authenticated on a given Compute Instance can be found in the Identity Token obtained from the metadata server that the GCP provisioner uses to obtain the Compute Instance identity and generate the SSH Host Certificate.
Allowing the GCP provisioner to issue SSH User Certificates would allow the above referred Workloads to use the smallstep infrastructure to sign into other Compute Instances. Examples of workloads that would benefit from this change are: CICD systems like Jenkins and Ansible.
Without this feature there would be two other options to achieve this:
- Have a separate JWK provisioner: This provisioner is …

Allowing GCP provisioner to issue SSH User Certificates - Option 2

---

authority/policy/engine.go

As discussed in https://github.com/smallstep/certificates/discussions/1950

Clarify SSH policy evaluation errors with opposing SSH cert type

---

authority/authority.go
authority/http_client.go
authority/http_client_test.go
authority/provisioner/azure.go
authority/provisioner/controller.go
authority/provisioner/controller_test.go
authority/provisioner/gcp.go
authority/provisioner/keystore.go
authority/provisioner/keystore_test.go
authority/provisioner/oidc.go
authority/provisioner/oidc_test.go
authority/provisioner/provisioner.go
authority/provisioner/utils_test.go
authority/provisioners.go

This commit allows the OIDC provisioner to be used with private identity providers using a certificate from step-ca.
Fixes #1909
cc: @tashian

Allow to use private  IdPs with the OIDC provisioner

---

api/api.go
api/api_test.go

This commit adds new endpoints that return the intermediate certificates used in the CA.
Related to #1848

Add endpoints that return intermediate certificates

---

logging/handler.go
logging/handler_test.go

Implements #1995
Please refer to #1995.
N/A
N/A
When step-ca is sitting behind a reverse proxy, e.g. AWS ALB, Cloudflare and so on.
N/A
It is worth noting that this feature is best not to be turned on when you can't trust the headers used, see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#security_and_privacy_concerns) for more info,
- https://github.com/smallstep/certificates/issues/1995
- The `realIP` function is mostly borrowed from [chi's realip middleware](https://github.com/go-chi/chi/blob/master/middleware/realip.go). 
💔Thank you!

Add option for the logging middleware to log real IP

---

authority/http_client.go
authority/http_client_test.go

This commit avoids an error starting the CA if the `http.DefaultTransport` is not an `*http.Transport`. If the DefaultTransport is overwritten, the newHTTPClient method will return a simple *http.Client. With an *http.Transport, it will return a client that trusts the system certificate pool and the CA roots.

Do not fail creating the provisioner HTTP client

---

authority/provisioner/aws.go
authority/provisioner/aws_test.go
authority/provisioner/azure.go
authority/provisioner/azure_test.go
authority/provisioner/gcp.go
authority/provisioner/gcp_test.go
authority/provisioner/sign_options.go
authority/provisioner/sign_options_test.go

... when disableCustomSANs is set to 'true'.
The DNS names in the certificate request must be a subset of the authorized set of DNS names (from the IID token). The previous functionality required that the DNS names in the certificate request exactly matched the authorized DNS names.

Use dnsNamesSubsetValidator for IID provisioners

---

authority/provisioner/scep.go
authority/provisioner/scep_test.go
authority/provisioner/sign_options.go
scep/api/api.go
scep/authority.go
scep/authority_test.go
scep/provisioner.go

This commit adds support for using template data from SCEPCHALLENGE webhooks.
This is a WIP

Add data support on SCEPCHALLENGE webhooks

---

acme/order.go
acme/order_test.go

This commit changes the urn suffix for acme errors to `urn:smallstep:acme:error:`

Change URN for acme errors

---

authority/provisioner/webhook.go
authority/provisioner/webhook_test.go
ca/ca.go
ca/identity/client.go
ca/identity/client_test.go
ca/identity/identity.go
internal/httptransport/httptransport.go
test/integration/scep/common_test.go

Currently, there's extensive cloning of what's stored in `http.DefaultTransport`, under the assumption that what's stored there is an `http.Transport` reference.
There are many reasons why that might not be the case, especially since the type of `http.DefaultTransport` is `http.RoundTripper` and _not_ `http.Transport`.
To that end, this PR introduces the `internal/httptransport` package and refactors the `authority`, `ca` & `test` packages to use it.

internal/httptransport: initial implementation of the package

---

authority/authority.go
authority/http_client.go
authority/http_client_test.go
authority/options.go
authority/provisioner/controller.go
authority/provisioner/controller_test.go
authority/provisioner/provisioner.go
authority/provisioner/scep.go
authority/provisioner/scep_test.go
authority/provisioner/webhook.go
authority/provisioner/webhook_test.go
authority/provisioners.go
ca/ca.go
internal/httptransport/httptransport.go

This PR adds references to a transport wrapper that callers may pass in order to inject their own dependecies to references of HTTP clients that the internal packages generate.

Transport wrappers

---

test/integration/requestid_test.go

The integration test checking for request IDs to be reflected depends on a test CA server to be started and running. At times (see [this case](https://github.com/smallstep/certificates/actions/runs/12642283670/job/35226696954?pr=2129) with a few attempts) the CA healthcheck would fail the test, presumably because the CA server was not running yet. This PR checks the connection a few times before failing the test.

Wait and retry connection to test CA server instead of failing (immediately)

---

commands/app.go
pki/pki.go

Update copy for linked CA init

---

ca/acmeClient.go
ca/acmeClient_test.go
ca/adminClient.go
ca/client.go
ca/client_test.go

This commit adds a new option to specify the client timeout to the CA client.
Fixes #2176

Add option to specify a client timeout

---

CHANGELOG.md
authority/provisioner/options_test.go
go.mod
go.sum

This PR upgrades go.step.sm/crypto with changes to use the key usage, extended key usage, and basic constraints from certificate requests in certificate templates.
Fixes #2260

Update go.step.sm/crypto with template improvements

---

authority/meter.go
authority/ssh.go
authority/tls.go
internal/metrix/meter.go

This commit passes the commit updates the Meter interface with SSH certificates and X.509 certificate chains. This allows us to add certificate specific things into the metrics. In this PR we are adding the SSH certificate type, user, or host.

Add SSH certificate type to metrics

---

api/api.go

This commit adds the default certificate SANs to the logs as a map.

Add the certificate sans to the logs

---

authority/authority.go
authority/authority_test.go
authority/http_client.go
authority/http_client_test.go
authority/options.go
authority/poolhttp/poolhttp.go
authority/poolhttp/poolhttp_test.go
authority/provisioner/controller.go
authority/provisioner/keystore.go
authority/provisioner/keystore_test.go
authority/provisioner/oidc.go
authority/provisioner/provisioner.go
authority/provisioner/scep.go
authority/provisioner/webhook.go
templates/templates.go

This commit replaces the client in provisioners and webhooks with an interface. Then it implements the interface using the new poolhttp package. This package implements the HTTPClient interface but it is backed by a sync.Pool, this improves memory, allowing the GC to clean more memory. It also removes the timer in the keystore to avoid having extra goroutines if a provisioner goes away. This commit avoids creating the templates func multiple times, reducing some memory in the heap.

Memory improvements
